"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-2e_gfd_ztkag64pm&q3n(f3uttqrso3^omss16*3agc#8dl=&7",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

# Origins (scheme + host) trusted for unsafe requests (admin/browsable-API
# POSTs over HTTPS). Required in production, e.g.
# https://www.carecircleinternal.com
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.getenv(
        "DJANGO_CSRF_TRUSTED_ORIGINS",
        "http://localhost:8000,http://127.0.0.1:8000",
    ).split(",")
    if o.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'corsheaders',
    'simple_history',

    # Local
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Exposes the current request to simple-history so changes are attributed
    # (api.history reads it lazily to set change source/actor).
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.getenv('DB_NAME', BASE_DIR / 'db.sqlite3'),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', ''),
        'PORT': os.getenv('DB_PORT', ''),
    }
}

# Add SSL options for RDS PostgreSQL connections
if os.getenv('DB_SSLMODE'):
    DATABASES['default']['OPTIONS'] = {
        'sslmode': os.getenv('DB_SSLMODE'),
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise: serve static files in production with compression + manifest.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api.authentication.AgentJWTAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
}

# Simple JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(
        minutes=int(os.getenv('JWT_ACCESS_MINUTES', '60'))
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(
        days=int(os.getenv('JWT_REFRESH_DAYS', '7'))
    ),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS
# Allow Chrome extensions (chrome-extension:// origins) and localhost for local dev
# In DEBUG mode, allow all origins for easier extension development
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = [
        o for o in os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:3000').split(',') if o
    ]
    # The Chrome extension calls the live API from a chrome-extension://<id>
    # origin. The id changes per install/build, so allow any extension origin
    # by regex rather than pinning a single id in CORS_ALLOWED_ORIGINS.
    CORS_ALLOWED_ORIGIN_REGEXES = [r"^chrome-extension://[a-p]{32}$"]


# ---------------------------------------------------------------------------
# GoHighLevel (GHL) CRM integration -- TEMPORARY. See api/integrations/ghl.
# Off by default; flip CRM_SYNC_ENABLED=true once GHL_PRIVATE_TOKEN +
# GHL_LOCATION_ID are set in the environment.
# ---------------------------------------------------------------------------
CRM_SYNC_ENABLED = os.getenv('CRM_SYNC_ENABLED', 'False').lower() == 'true'
GHL_PRIVATE_TOKEN = os.getenv('GHL_PRIVATE_TOKEN', '')
GHL_LOCATION_ID = os.getenv('GHL_LOCATION_ID', '')
GHL_API_BASE = os.getenv('GHL_API_BASE', 'https://services.leadconnectorhq.com')
GHL_API_VERSION = os.getenv('GHL_API_VERSION', '2021-07-28')
GHL_TIMEOUT = int(os.getenv('GHL_TIMEOUT', '10'))
GHL_CONTACT_SOURCE = os.getenv('GHL_CONTACT_SOURCE', 'Benefully extension')


# ---------------------------------------------------------------------------
# CallTools dialer integration. See api/integrations/calltools.
# Auth: "Authorization: Token <CALLTOOLS_API_TOKEN>". Base URL is the per-silo
# subdomain of calltools.io (e.g. https://east-1.calltools.io/api).
# ---------------------------------------------------------------------------
CALLTOOLS_API_TOKEN = os.getenv('CALLTOOLS_API_TOKEN', '')
CALLTOOLS_API_BASE = os.getenv('CALLTOOLS_API_BASE', 'https://east-1.calltools.io/api')
CALLTOOLS_TIMEOUT = int(os.getenv('CALLTOOLS_TIMEOUT', '15'))


# ---------------------------------------------------------------------------
# Field-level encryption (Unite Us tokens at rest). A urlsafe base64 32-byte
# Fernet key. Generate with:
#   python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# Required at runtime to read/write encrypted columns; NOT needed for migrations.
# ---------------------------------------------------------------------------
FIELD_ENCRYPTION_KEY = os.getenv('FIELD_ENCRYPTION_KEY', '')


# ---------------------------------------------------------------------------
# Unite Us API integration (daily data pull). The backend stores per-provider
# credentials captured by the extension and refreshes them via the OAuth
# refresh-token grant. Endpoint specifics are confirmed via the extension's
# auth-capture (window.__uwCapture(true)).
# ---------------------------------------------------------------------------
UNITEUS_ENABLED = os.getenv('UNITEUS_ENABLED', 'False').lower() == 'true'
UNITEUS_TOKEN_URL = os.getenv('UNITEUS_TOKEN_URL', '')  # OAuth token endpoint
UNITEUS_CLIENT_ID = os.getenv('UNITEUS_CLIENT_ID', '')
UNITEUS_CLIENT_SECRET = os.getenv('UNITEUS_CLIENT_SECRET', '')  # blank for PKCE/public
UNITEUS_API_BASE = os.getenv('UNITEUS_API_BASE', 'https://core.uniteus.io')
UNITEUS_TIMEOUT = int(os.getenv('UNITEUS_TIMEOUT', '30'))
# Refresh the access token when it expires within this many seconds.
UNITEUS_REFRESH_SKEW = int(os.getenv('UNITEUS_REFRESH_SKEW', '120'))
