"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path

from celery.schedules import crontab
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-2e_gfd_ztkag64pm&q3n(f3uttqrso3^omss16*3agc#8dl=&7",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if h.strip()
]


def _ec2_private_ip():
    """Best-effort EC2 instance private IPv4, so ELB/ALB health checks -- which
    hit the instance by IP (not the domain) -- don't 400 with DisallowedHost and
    mark the target unhealthy. The IP can change on stop/start, so we resolve it
    at startup rather than pinning it in .env. Returns "" off EC2 / on failure.

    Tries IMDSv2 first (token-required), then IMDSv1, then a hostname lookup."""
    import urllib.request

    imds = "http://169.254.169.254/latest"
    try:
        token_req = urllib.request.Request(
            f"{imds}/api/token",
            method="PUT",
            headers={"X-aws-ec2-metadata-token-ttl-seconds": "60"},
        )
        token = urllib.request.urlopen(token_req, timeout=0.3).read().decode()
        ip_req = urllib.request.Request(
            f"{imds}/meta-data/local-ipv4",
            headers={"X-aws-ec2-metadata-token": token},
        )
        return urllib.request.urlopen(ip_req, timeout=0.3).read().decode().strip()
    except Exception:
        pass
    try:  # IMDSv1 (older instances / IMDSv2 not enforced)
        return urllib.request.urlopen(
            f"{imds}/meta-data/local-ipv4", timeout=0.3
        ).read().decode().strip()
    except Exception:
        pass
    try:  # last resort: whatever the hostname resolves to
        import socket

        return socket.gethostbyname(socket.gethostname())
    except OSError:
        return ""


# Only bother when not explicitly disabled (e.g. local dev sets it to skip the
# metadata probe). Appended, never replacing the operator-provided hosts.
if os.getenv("DJANGO_AUTODETECT_HOST_IP", "True").lower() == "true":
    _ip = _ec2_private_ip()
    if _ip and _ip not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_ip)

# Origins (scheme + host) trusted for unsafe requests (admin/browsable-API
# POSTs over HTTPS). Required in production, e.g.
# https://www.carecircleinternal.com
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.getenv(
        "DJANGO_CSRF_TRUSTED_ORIGINS",
        "http://localhost:8000,http://127.0.0.1:8000",
    ).split(",")
    if o.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',

    # Third-party
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'corsheaders',
    'simple_history',
    'storages',

    # Local
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Exposes the current request to simple-history so changes are attributed
    # (api.history reads it lazily to set change source/actor).
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.getenv('DB_NAME', 'carecircle'),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', ''),
        'PORT': os.getenv('DB_PORT', ''),
        # Persistent connections: reuse a connection across requests instead of
        # opening a NEW one (TCP + TLS + Postgres auth handshake to RDS) on every
        # single request. With CONN_MAX_AGE=0 (the Django default) that per-request
        # handshake dominated latency and, when it stalled, blocked gunicorn
        # workers -- making the whole app slow while CPU and query-time stayed
        # near zero. Env-tunable; 0 restores per-request connections.
        'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '60')),
        # Verify a reused connection is still usable at the start of each request
        # and transparently reconnect if the server dropped it (RDS idle timeout,
        # failover, restart). Prevents persistent connections from serving a dead
        # socket. (Django 4.1+.)
        'CONN_HEALTH_CHECKS': os.getenv('DB_CONN_HEALTH_CHECKS', 'true').lower() == 'true',
    }
}

# PostgreSQL/RDS connection options (only when SSL is configured, i.e. not a
# local unencrypted Postgres). ``connect_timeout`` makes a stalled connection attempt
# fail in seconds instead of tying up a gunicorn worker until its 300s timeout
# when RDS is slow to accept a new connection.
if os.getenv('DB_SSLMODE'):
    DATABASES['default']['OPTIONS'] = {
        'sslmode': os.getenv('DB_SSLMODE'),
        'connect_timeout': int(os.getenv('DB_CONNECT_TIMEOUT', '10')),
    }

# ---------------------------------------------------------------------------
# Test database
# ---------------------------------------------------------------------------
# The test suite runs on PostgreSQL (Django creates/drops a ``test_<DB_NAME>``
# database), so tests exercise REAL Postgres behavior -- column length limits,
# transaction semantics -- catching bugs a SQLite test DB would silently mask.
# The schema is built DIRECTLY from the current models (migrations disabled) both
# for speed and to sidestep a historical migration
# (0036_rename_eligibility_to_assessment) that only needs Postgres' in-place
# column rename. Opt in automatically for `manage.py test`, or explicitly via
# DISABLE_MIGRATIONS=1.
RUNNING_TESTS = "test" in sys.argv or os.getenv("DISABLE_MIGRATIONS") == "1"
if RUNNING_TESTS:
    class _DisableMigrations:
        def __contains__(self, item):
            return True

        def __getitem__(self, item):
            return None  # None -> create tables straight from model state

    MIGRATION_MODULES = _DisableMigrations()


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# The program operates on the New York calendar (Met Council / NYC), and the
# server runs in America/New_York. With USE_TZ=True datetimes are still STORED
# in UTC; TIME_ZONE only governs the *active* zone used for date extraction and
# rendering -- i.e. `timezone.localdate()`, `localtime()`, and `__date` lookups.
# Keeping this as UTC made the Verification page's Requested/Completed date
# filters (and the "Today/Yesterday/..." period ranges) match the wrong day for
# evening-EDT records (a 9pm EDT event stored as next-day UTC). Anchoring to
# America/New_York makes those filters agree with the local calendar.
TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ---------------------------------------------------------------------------
# Object storage (S3)
# ---------------------------------------------------------------------------
# S3 is the DEFAULT file storage in production (large import uploads + future
# document storage); local dev keeps the filesystem. Toggle with DJANGO_USE_S3
# (defaults on whenever a bucket is configured and DEBUG is off). Credentials
# are best supplied by the EC2 instance role -- leave the key envs unset and
# boto3 will use the role automatically.
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME", "")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "us-east-1")
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID", "") or None
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY", "") or None
# Optional custom endpoint (e.g. a local MinIO at http://127.0.0.1:9000) so the
# full presign -> upload -> Celery flow can run against S3-compatible storage in
# dev. Leave unset to use real AWS S3.
AWS_S3_ENDPOINT_URL = os.getenv("AWS_S3_ENDPOINT_URL", "") or None

USE_S3 = os.getenv(
    "DJANGO_USE_S3",
    "true" if (AWS_STORAGE_BUCKET_NAME and not DEBUG) else "false",
).lower() == "true"

# Common S3 options: keep objects private and served via short-lived signed
# URLs; never silently overwrite; import uploads live under the imports/ prefix
# and are set per-file, general media under media/.
AWS_DEFAULT_ACL = None            # bucket owner enforced / private
AWS_QUERYSTRING_AUTH = True       # signed URLs for private objects
AWS_S3_FILE_OVERWRITE = False
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_LOCATION = "media"            # default prefix for FileField uploads

if USE_S3:
    _default_storage = {
        'BACKEND': 'storages.backends.s3.S3Storage',
        'OPTIONS': {
            'bucket_name': AWS_STORAGE_BUCKET_NAME,
            'region_name': AWS_S3_REGION_NAME,
            'location': AWS_LOCATION,
            'default_acl': AWS_DEFAULT_ACL,
            'file_overwrite': AWS_S3_FILE_OVERWRITE,
            'querystring_auth': AWS_QUERYSTRING_AUTH,
            'signature_version': AWS_S3_SIGNATURE_VERSION,
            **({'endpoint_url': AWS_S3_ENDPOINT_URL} if AWS_S3_ENDPOINT_URL else {}),
        },
    }
else:
    _default_storage = {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    }

# WhiteNoise: serve static files in production with compression + manifest.
STORAGES = {
    'default': _default_storage,
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# ---------------------------------------------------------------------------
# Celery (async imports + smart diagnostics)
# ---------------------------------------------------------------------------
# Redis broker/result backend. Starts on the same EC2 (redis://127.0.0.1);
# point CELERY_BROKER_URL at ElastiCache later with no code change. Long imports
# run in the worker, so we favour reliability (late ack, prefetch=1) over
# throughput and recycle child processes to bound memory after big files.
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://127.0.0.1:6379/1")
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 100
CELERY_TASK_TRACK_STARTED = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
# The daily warning-snapshot sweep is scheduled by wall-clock time, so anchor
# Beat to the program's operating calendar (America/New_York). Interval-based
# entries (e.g. the export poller) are unaffected; only crontab entries follow
# this zone. Beat still tracks DST automatically.
CELERY_TIMEZONE = "America/New_York"

# Beat schedule. The Unite Us export poller advances requested exports through
# download -> S3 -> import; exports take a few minutes to generate, so a short
# cadence keeps latency low without hammering the API. Requesting exports is
# UI/manual-triggered (or via api.tasks.request_uniteus_exports on demand).
CELERY_BEAT_SCHEDULE = {
    "poll-uniteus-exports": {
        "task": "api.tasks.poll_uniteus_exports",
        "schedule": float(os.getenv("UNITEUS_EXPORT_POLL_SECONDS", "300")),
    },
    # Daily safety-net sweep so time-based warnings (e.g. an insurance or
    # authorization that lapses with the passing of a day) re-evaluate even when
    # no write re-triggers them. Runs at 11:00 America/New_York.
    "sync-member-warnings": {
        "task": "api.tasks.sync_member_warnings",
        "schedule": crontab(minute=0, hour=11),
    },
    # Daily safety-net sweep: cancel service for clients whose LAST internal-
    # service case has closed but whose enrollment was never terminalized (a
    # historical closure the close-out never re-evaluated). Idempotent -- a no-op
    # once clean. Runs at 04:00 America/New_York, after the 02:00 daily_pull and
    # BEFORE the 05:00 delivery-calendar sync, so cancelled households drop off
    # the calendar before the day's PO work.
    "sweep-closed-case-service": {
        "task": "api.tasks.sweep_closed_case_service",
        "schedule": crontab(minute=0, hour=4),
    },
    # Daily delivery-calendar reconcile so no eligible member is missing from
    # upcoming Purchase Orders (members added get scheduled; paused/removed get
    # dropped). Runs at 05:00 America/New_York, after the 02:00 daily_pull import
    # so overnight member changes are reflected before the day's PO work.
    "sync-delivery-calendars": {
        "task": "api.tasks.sync_delivery_calendars",
        "schedule": crontab(minute=0, hour=5),
    },
    # Nightly assessment-results enrichment: fills eligible_services (and thus
    # Client Level 1/2) on assessments that the CSV import lands without results.
    # Runs at 03:30 America/New_York -- after the 02:00 pull, before the 04:00
    # closed-case sweep. No-op unless UNITEUS_ASSESSMENT_API_ENABLED is set.
    "import-uniteus-assessment-results": {
        "task": "api.tasks.import_uniteus_assessment_results",
        "schedule": crontab(minute=30, hour=3),
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api.authentication.AgentJWTAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
}

# Simple JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(
        minutes=int(os.getenv('JWT_ACCESS_MINUTES', '60'))
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(
        days=int(os.getenv('JWT_REFRESH_DAYS', '7'))
    ),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS
# Allow Chrome extensions (chrome-extension:// origins) and localhost for local dev
# In DEBUG mode, allow all origins for easier extension development
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = [
        o.strip()
        for o in os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:3000').split(',')
        if o.strip()
    ]
    # The Chrome extension calls the live API from a chrome-extension://<id>
    # origin. The id changes per install/build, so allow any extension origin
    # by regex rather than pinning a single id in CORS_ALLOWED_ORIGINS.
    #
    # The Unite Us content script (extension/content/uniteus.js) POSTs the
    # captured session to /api/uniteus/credentials/ from the app.uniteus.io page
    # origin (MV3 content-script fetches are CORS-checked against the page
    # origin), so that origin must be allowed too. The endpoint is still
    # token-authenticated.
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^chrome-extension://[a-p]{32}$",
        r"^https://app\.uniteus\.io$",
    ]


# ---------------------------------------------------------------------------
# Reverse proxy / TLS (nginx terminates HTTPS in production).
# nginx forwards "X-Forwarded-Proto: https", so tell Django the request is
# secure. Without this, request.is_secure() is False and the admin/browsable
# API CSRF check fails for HTTPS POSTs ("CSRF verification failed").
# Requires nginx to set: proxy_set_header X-Forwarded-Proto $scheme;
# ---------------------------------------------------------------------------
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    # Cookies should only travel over HTTPS in production.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# ---------------------------------------------------------------------------
# GoHighLevel (GHL) CRM integration -- TEMPORARY. See api/integrations/ghl.
# Off by default; flip CRM_SYNC_ENABLED=true once GHL_PRIVATE_TOKEN +
# GHL_LOCATION_ID are set in the environment.
#
# MVP phase: CRM_SYNC_DISCONNECTED hard-disconnects ALL outbound syncing to the
# external CRM (overrides CRM_SYNC_ENABLED). Defaults to True so no data leaves
# our API during the MVP. Set CRM_SYNC_DISCONNECTED=false to re-enable.
# ---------------------------------------------------------------------------
CRM_SYNC_DISCONNECTED = os.getenv('CRM_SYNC_DISCONNECTED', 'True').lower() == 'true'
CRM_SYNC_ENABLED = os.getenv('CRM_SYNC_ENABLED', 'False').lower() == 'true'
GHL_PRIVATE_TOKEN = os.getenv('GHL_PRIVATE_TOKEN', '')
GHL_LOCATION_ID = os.getenv('GHL_LOCATION_ID', '')
GHL_API_BASE = os.getenv('GHL_API_BASE', 'https://services.leadconnectorhq.com')
GHL_API_VERSION = os.getenv('GHL_API_VERSION', '2021-07-28')
GHL_TIMEOUT = int(os.getenv('GHL_TIMEOUT', '10'))
GHL_CONTACT_SOURCE = os.getenv('GHL_CONTACT_SOURCE', 'Benefully extension')


# ---------------------------------------------------------------------------
# CallTools dialer integration. See api/integrations/calltools.
# Auth: "Authorization: Token <CALLTOOLS_API_TOKEN>". Base URL is the per-silo
# subdomain of calltools.io (e.g. https://east-1.calltools.io/api).
# ---------------------------------------------------------------------------
CALLTOOLS_API_TOKEN = os.getenv('CALLTOOLS_API_TOKEN', '')
CALLTOOLS_API_BASE = os.getenv('CALLTOOLS_API_BASE', 'https://east-1.calltools.io/api')
CALLTOOLS_TIMEOUT = int(os.getenv('CALLTOOLS_TIMEOUT', '15'))


# ---------------------------------------------------------------------------
# Mailgun transactional email (agent login 2FA codes). See api/integrations/mailgun.
# Auth: HTTP basic ("api", MAILGUN_API_KEY). MAILGUN_DOMAIN is the sending domain
# (a sandbox sandboxXXXX.mailgun.org for testing, or a verified domain in prod).
# MAILGUN_FROM overrides the From header; defaults to postmaster@<domain>.
# ---------------------------------------------------------------------------
MAILGUN_API_KEY = os.getenv('MAILGUN_API_KEY', '')
MAILGUN_DOMAIN = os.getenv('MAILGUN_DOMAIN', '')
MAILGUN_FROM = os.getenv('MAILGUN_FROM', '')
MAILGUN_API_BASE = os.getenv('MAILGUN_API_BASE', 'https://api.mailgun.net')
MAILGUN_TIMEOUT = int(os.getenv('MAILGUN_TIMEOUT', '15'))

# ---------------------------------------------------------------------------
# Google Places (New) — proxied server-side for the extension's doctor-address
# autocomplete. Keeping the key here (never shipped to the client) avoids MV3
# remote-script CSP issues and keeps the key restricted to our backend.
# ---------------------------------------------------------------------------
GOOGLE_MAP_KEY = os.getenv('GOOGLE_MAP_KEY', '')

# Agent login 2FA code policy.
AGENT_2FA_CODE_TTL_SECONDS = int(os.getenv('AGENT_2FA_CODE_TTL_SECONDS', '600'))
AGENT_2FA_RESEND_COOLDOWN_SECONDS = int(
    os.getenv('AGENT_2FA_RESEND_COOLDOWN_SECONDS', '30')
)
AGENT_2FA_MAX_ATTEMPTS = int(os.getenv('AGENT_2FA_MAX_ATTEMPTS', '5'))


# ---------------------------------------------------------------------------
# Field-level encryption (Unite Us tokens at rest). A urlsafe base64 32-byte
# Fernet key. Generate with:
#   python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# Required at runtime to read/write encrypted columns; NOT needed for migrations.
# ---------------------------------------------------------------------------
FIELD_ENCRYPTION_KEY = os.getenv('FIELD_ENCRYPTION_KEY', '')


# ---------------------------------------------------------------------------
# Unite Us API integration (daily data pull). The backend stores per-provider
# credentials captured by the extension and refreshes them via the OAuth
# refresh-token grant. Endpoint specifics are confirmed via the extension's
# auth-capture (window.__uwCapture(true)).
# ---------------------------------------------------------------------------
UNITEUS_ENABLED = os.getenv('UNITEUS_ENABLED', 'False').lower() == 'true'
UNITEUS_TOKEN_URL = os.getenv('UNITEUS_TOKEN_URL', '')  # OAuth token endpoint
UNITEUS_CLIENT_ID = os.getenv('UNITEUS_CLIENT_ID', '')
UNITEUS_CLIENT_SECRET = os.getenv('UNITEUS_CLIENT_SECRET', '')  # blank for PKCE/public
UNITEUS_API_BASE = os.getenv('UNITEUS_API_BASE', 'https://core.uniteus.io')
# Host that serves assessment/screening RESULTS (eligible_services), distinct
# from the core JSON:API host above. Same session bearer + provider/employee ids.
UNITEUS_SCREENINGS_INGESTION_BASE = os.getenv(
    'UNITEUS_SCREENINGS_INGESTION_BASE', 'https://screenings-ingestion.uniteus.io'
)
# Master switch for the headless assessment-results enrichment (nightly pull of
# eligible_services from the ingestion host). OFF until validated in prod.
UNITEUS_ASSESSMENT_API_ENABLED = (
    os.getenv('UNITEUS_ASSESSMENT_API_ENABLED', 'False').lower() == 'true'
)
UNITEUS_TIMEOUT = int(os.getenv('UNITEUS_TIMEOUT', '30'))
# Refresh the access token when it expires within this many seconds.
UNITEUS_REFRESH_SKEW = int(os.getenv('UNITEUS_REFRESH_SKEW', '120'))
# On-demand ("Sync Now") pull from the extension. OFF by default: it runs the
# full import inline in a gunicorn worker thread and can exhaust all workers
# (site-wide 504s + ALB health-check flapping). The nightly `daily_pull` cron
# keeps data fresh. Only re-enable once the pull runs off the request path.
UNITEUS_ONDEMAND_SYNC_ENABLED = (
    os.getenv('UNITEUS_ONDEMAND_SYNC_ENABLED', 'False').lower() == 'true'
)


# ---------------------------------------------------------------------------
# Logging. Django's default config only writes to the console when DEBUG=True
# (the console handler is gated by require_debug_true) and otherwise relies on
# mail_admins -- so with DEBUG=False and no email backend, unhandled 500
# tracebacks are silently dropped. This config always logs to the console
# (captured by gunicorn -> journald) so server errors are visible in production.
# LOG_LEVEL defaults to INFO; set LOG_LEVEL=WARNING in prod to quiet it down.
# ---------------------------------------------------------------------------
LOG_LEVEL = os.getenv('LOG_LEVEL', 'INFO').upper()
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        # Always log request errors (5xx tracebacks) regardless of DEBUG.
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
