# Generated by Django 6.0.5 on 2026-06-02 16:09

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('created_by_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('crm_contact_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=120)),
                ('middle_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('suffix', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('nonbinary', 'Non-binary'), ('transgender', 'Transgender'), ('other', 'Other'), ('declined', 'Declined to answer'), ('unknown', 'Unknown')], max_length=20)),
                ('sexuality', models.CharField(blank=True, max_length=50)),
                ('sexuality_other', models.CharField(blank=True, max_length=120)),
                ('race', models.CharField(blank=True, max_length=100)),
                ('ethnicity', models.CharField(blank=True, max_length=100)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('partnered', 'Partnered'), ('separated', 'Separated'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('unknown', 'Unknown')], max_length=20)),
                ('citizenship', models.CharField(blank=True, max_length=100)),
                ('time_zone', models.CharField(default='America/New_York', max_length=64)),
                ('enrollment_from', models.CharField(default='Unite Us', max_length=120)),
                ('consent_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('gross_monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('household_size', models.PositiveIntegerField(blank=True, null=True)),
                ('adults_in_household', models.PositiveIntegerField(blank=True, null=True)),
                ('children_in_household', models.PositiveIntegerField(blank=True, null=True)),
                ('preferred_communication_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('text', 'Text'), ('mail', 'Mail')], max_length=20)),
                ('preferred_communication_time_of_day', models.JSONField(blank=True, default=api.models.default_communication_time_of_day)),
                ('preferred_spoken_language', models.CharField(blank=True, max_length=80)),
                ('preferred_written_language', models.CharField(blank=True, max_length=80)),
                ('communication_channel', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('text', 'Text'), ('mail', 'Mail')], max_length=20)),
                ('phone_type', models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('home', 'Home'), ('work', 'Work')], default='mobile', max_length=10)),
                ('client_phone_number', models.CharField(blank=True, max_length=32)),
                ('client_email_address', models.EmailField(blank=True, max_length=254)),
                ('care_coordinator', models.CharField(blank=True, max_length=255)),
                ('care_coordinator_status', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='api_client_last_na_0f0309_idx'), models.Index(fields=['date_of_birth'], name='api_client_date_of_4028f5_idx'), models.Index(fields=['created_by_id'], name='api_client_created_49adcd_idx'), models.Index(fields=['is_active'], name='api_client_is_acti_a276a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='MilitaryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('military_affiliation', models.CharField(blank=True, choices=[('service_member', 'Service Member'), ('veteran', 'Veteran'), ('family_member', 'Family Member of Service Member/Veteran'), ('none', 'No Military Affiliation'), ('declined', 'Declined to answer')], max_length=20)),
                ('military_entry_date', models.DateField(blank=True, null=True)),
                ('military_exit_date', models.DateField(blank=True, null=True)),
                ('current_status', models.CharField(blank=True, max_length=80)),
                ('currently_transitioning', models.BooleanField(blank=True, null=True)),
                ('at_least_one_day_active_duty', models.BooleanField(blank=True, null=True)),
                ('deployed', models.BooleanField(blank=True, null=True)),
                ('deployment_start_date', models.DateField(blank=True, null=True)),
                ('deployment_end_date', models.DateField(blank=True, null=True)),
                ('branch', models.CharField(blank=True, choices=[('army', 'Army'), ('navy', 'Navy'), ('air_force', 'Air Force'), ('marines', 'Marine Corps'), ('coast_guard', 'Coast Guard'), ('space_force', 'Space Force'), ('national_guard', 'National Guard'), ('reserves', 'Reserves')], max_length=20)),
                ('service_era', models.CharField(blank=True, max_length=80)),
                ('discharge_type', models.CharField(blank=True, choices=[('honorable', 'Honorable'), ('general', 'General (Under Honorable Conditions)'), ('other_than_honorable', 'Other Than Honorable'), ('bad_conduct', 'Bad Conduct'), ('dishonorable', 'Dishonorable'), ('uncharacterized', 'Uncharacterized')], max_length=30)),
                ('discharged_due_to_disability', models.BooleanField(blank=True, null=True)),
                ('service_connected_disability', models.BooleanField(blank=True, null=True)),
                ('service_connected_disability_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('proof_of_veteran_status', models.BooleanField(blank=True, null=True)),
                ('proof_type', models.CharField(blank=True, max_length=120)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='military_profile', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('current', 'Current'), ('mailing', 'Mailing')], default='current', max_length=10)),
                ('is_mailing_address', models.BooleanField(default=False)),
                ('line1', models.CharField(blank=True, max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('county', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('state', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('added_by_name', models.CharField(blank=True, max_length=255)),
                ('validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='api.client')),
            ],
            options={
                'ordering': ['-is_active', 'address_type'],
                'indexes': [models.Index(fields=['client', 'address_type', 'is_active'], name='api_address_client__6ac7c9_idx'), models.Index(fields=['postal_code'], name='api_address_postal__5aff79_idx')],
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_external_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('plan_type', models.CharField(blank=True, choices=[('medicaid', 'Medicaid'), ('medicare', 'Medicare'), ('commercial', 'Commercial'), ('marketplace', 'Marketplace'), ('dual', 'Dual (Medicare/Medicaid)'), ('self_pay', 'Self Pay'), ('other', 'Other')], max_length=20)),
                ('plan_name', models.CharField(blank=True, max_length=255)),
                ('insurance_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('pending', 'Pending'), ('inactive', 'Inactive'), ('expired', 'Expired')], max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('external_group_id', models.CharField(blank=True, max_length=64)),
                ('external_member_id', models.CharField(blank=True, max_length=64)),
                ('ingested', models.BooleanField(default=False)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('record_status', models.CharField(blank=True, choices=[('active', 'Active'), ('pending', 'Pending'), ('inactive', 'Inactive'), ('expired', 'Expired')], max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='api.client')),
            ],
            options={
                'ordering': ['-is_primary', '-enrolled_at'],
                'indexes': [models.Index(fields=['client', 'status'], name='api_insuran_client__929872_idx'), models.Index(fields=['insurance_id'], name='api_insuran_insuran_23f9d5_idx')],
            },
        ),
    ]
