# Generated by Django 6.0.5 on 2026-06-02 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('network_id', models.UUIDField(blank=True, null=True)),
                ('network_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['network_id'], name='api_provide_network_09d4e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='api.provider')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('client_first_name', models.CharField(blank=True, max_length=120)),
                ('client_last_name', models.CharField(blank=True, max_length=120)),
                ('client_dob', models.DateField(blank=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('created_by_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('product_id', models.UUIDField(blank=True, null=True)),
                ('user_entered_opened_date', models.DateField(blank=True, null=True)),
                ('user_entered_closed_date', models.DateField(blank=True, null=True)),
                ('ar_submitted_on', models.DateTimeField(blank=True, null=True)),
                ('case_processed_at', models.DateTimeField(blank=True, null=True)),
                ('case_managed_at', models.DateTimeField(blank=True, null=True)),
                ('case_off_platform_at', models.DateTimeField(blank=True, null=True)),
                ('case_closed_at', models.DateTimeField(blank=True, null=True)),
                ('case_description', models.TextField(blank=True)),
                ('case_status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('pending_authorization', 'Pending Authorization'), ('managed', 'Managed'), ('off_platform', 'Off Platform'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=25)),
                ('closed_note', models.TextField(blank=True)),
                ('started_as_assistance_request', models.BooleanField(default=False)),
                ('case_is_referred', models.BooleanField(default=False)),
                ('network_id', models.UUIDField(blank=True, null=True)),
                ('network_name', models.CharField(blank=True, max_length=255)),
                ('originating_provider_name', models.CharField(blank=True, max_length=255)),
                ('provider_name', models.CharField(blank=True, max_length=255)),
                ('out_of_network_provider_name', models.CharField(blank=True, max_length=255)),
                ('program_name', models.CharField(blank=True, max_length=255)),
                ('primary_worker_id', models.UUIDField(blank=True, null=True)),
                ('primary_worker_name', models.CharField(blank=True, max_length=255)),
                ('care_coordinator', models.CharField(blank=True, max_length=255)),
                ('care_coordinator_status', models.CharField(blank=True, max_length=80)),
                ('service_type', models.CharField(blank=True, db_index=True, max_length=120)),
                ('service_subtype', models.CharField(blank=True, max_length=120)),
                ('outcome_id', models.UUIDField(blank=True, null=True)),
                ('outcome_description', models.TextField(blank=True)),
                ('outcome_resolution_type', models.CharField(blank=True, choices=[('resolved', 'Resolved'), ('unresolved', 'Unresolved'), ('referred_out', 'Referred Out'), ('no_longer_needed', 'No Longer Needed'), ('unable_to_contact', 'Unable to Contact'), ('ineligible', 'Ineligible'), ('other', 'Other')], max_length=20)),
                ('service_authorization_status', models.CharField(blank=True, choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('expired', 'Expired')], max_length=20)),
                ('service_authorization_request_starts_at', models.DateTimeField(blank=True, null=True)),
                ('service_authorization_request_ends_at', models.DateTimeField(blank=True, null=True)),
                ('service_authorization_approval_starts_at', models.DateTimeField(blank=True, null=True)),
                ('service_authorization_approval_ends_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='api.client')),
                ('previous_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_cases', to='api.case')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='api.program')),
                ('originating_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originated_cases', to='api.provider')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serviced_cases', to='api.provider')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'case_status'], name='api_case_client__cba7c1_idx'), models.Index(fields=['provider'], name='api_case_provide_510e63_idx'), models.Index(fields=['originating_provider'], name='api_case_origina_ba6822_idx'), models.Index(fields=['program'], name='api_case_program_b58f68_idx'), models.Index(fields=['case_status'], name='api_case_case_st_c7990c_idx'), models.Index(fields=['created_by_id'], name='api_case_created_0249c8_idx')],
            },
        ),
    ]
