# Generated by Django 6.0.5 on 2026-06-02 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_screentemplate_screening_question_verifiedsocialneed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='data_pulled_at',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='pull_end_date',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='pull_start_date',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='pull_timestamp',
        ),
        migrations.AddField(
            model_name='answer',
            name='question_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='api.questionoption'),
        ),
        migrations.AddField(
            model_name='case',
            name='export_provider_role',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('clients', 'Clients'), ('cases', 'Cases'), ('screenings', 'Screenings')], max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('pull_start_date', models.DateField(blank=True, null=True)),
                ('pull_end_date', models.DateField(blank=True, null=True)),
                ('pull_timestamp', models.DateTimeField(blank=True, null=True)),
                ('data_pulled_at', models.DateTimeField(blank=True, null=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_log', models.TextField(blank=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='api.importbatch'),
        ),
        migrations.AddField(
            model_name='client',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='api.importbatch'),
        ),
        migrations.AddField(
            model_name='screening',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenings', to='api.importbatch'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['source', 'status'], name='api_importb_source_8f496c_idx'),
        ),
    ]
