# Generated by Django 6.0.5 on 2026-06-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_screening_data_pulled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='agent_code',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='client',
            name='attestation_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='call_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='different_delivery_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='eligible_for',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='client',
            name='is_family',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='lead_source',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='client',
            name='referred_for',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='client',
            name='total_family_members',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('current', 'Current'), ('mailing', 'Mailing'), ('delivery', 'Delivery')], default='current', max_length=10),
        ),
    ]
