# Generated by Django 6.0.5 on 2026-06-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_client_agent_code_client_attestation_needed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='call_transfer_answered',
            field=models.CharField(blank=True, choices=[('transfer_successful', 'Transfer Successful (Verification Agent Answered)'), ('transfer_failed', 'Transfer Failed (No Answer)'), ('no_verification_needed', 'No Verification Needed')], max_length=30),
        ),
    ]
