# Generated by Django 6.0.5 on 2026-06-02 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_client_call_transfer_answered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('eligibility_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('subject_id', models.UUIDField(db_index=True)),
                ('subject_type', models.CharField(blank=True, max_length=50)),
                ('active_screen', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to_id', models.UUIDField(blank=True, null=True)),
                ('screen_created_at', models.DateTimeField(blank=True, null=True)),
                ('screen_updated_at', models.DateTimeField(blank=True, null=True)),
                ('screen_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], max_length=20)),
                ('screen_status_at', models.DateTimeField(blank=True, null=True)),
                ('screen_type', models.CharField(blank=True, choices=[('standard', 'Standard'), ('enhanced', 'Enhanced'), ('eligibility', 'Eligibility'), ('assessment', 'Assessment'), ('reassessment', 'Reassessment'), ('follow_up', 'Follow Up')], max_length=20)),
                ('screen_source', models.CharField(blank=True, max_length=120)),
                ('client_first_name', models.CharField(blank=True, max_length=120)),
                ('client_last_name', models.CharField(blank=True, max_length=120)),
                ('client_dob', models.DateField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('facilitator_id', models.UUIDField(blank=True, null=True)),
                ('facilitator_type', models.CharField(blank=True, max_length=50)),
                ('provider_id', models.UUIDField(blank=True, null=True)),
                ('provider_name', models.CharField(blank=True, max_length=255)),
                ('performing_organization_name', models.CharField(blank=True, max_length=255)),
                ('outreach_count', models.PositiveIntegerField(default=0)),
                ('outreach_status', models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('attempted', 'Attempted'), ('reached', 'Reached'), ('unreachable', 'Unreachable'), ('completed', 'Completed')], max_length=20)),
                ('decline_note', models.TextField(blank=True)),
                ('decline_reason_id', models.UUIDField(blank=True, null=True)),
                ('decline_primary_text', models.CharField(blank=True, max_length=255)),
                ('decline_secondary_text', models.CharField(blank=True, max_length=255)),
                ('decline_reason_key', models.CharField(blank=True, max_length=120)),
                ('interpreter_id', models.UUIDField(blank=True, null=True)),
                ('interpreter_type', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(blank=True, max_length=80)),
                ('consent', models.BooleanField(blank=True, null=True)),
                ('consent_code', models.CharField(blank=True, max_length=80)),
                ('interpersonal_safety_riskscore', models.FloatField(blank=True, null=True)),
                ('interpersonal_safety_interpretation', models.CharField(blank=True, max_length=255)),
                ('screen_snomed_codes', models.JSONField(blank=True, default=list)),
                ('screen_icd10_codes', models.JSONField(blank=True, default=list)),
                ('clinical_code_classification', models.CharField(blank=True, max_length=120)),
                ('verified_clinical_code', models.CharField(blank=True, max_length=50)),
                ('verified_clinical_code_description', models.CharField(blank=True, max_length=255)),
                ('eligible_status', models.CharField(blank=True, max_length=50)),
                ('eligible_services', models.JSONField(blank=True, default=list)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by_id', models.UUIDField(blank=True, null=True)),
                ('verified_by_type', models.CharField(blank=True, max_length=50)),
                ('is_case_sensitive', models.BooleanField(default=False)),
                ('filter_date', models.DateField(blank=True, null=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibilities', to='api.case')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibilities', to='api.client')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibilities', to='api.importbatch')),
            ],
            options={
                'verbose_name_plural': 'eligibilities',
                'ordering': ['-screen_created_at'],
                'indexes': [models.Index(fields=['subject_id'], name='api_eligibi_subject_edf179_idx'), models.Index(fields=['client', 'screen_status'], name='api_eligibi_client__074e12_idx'), models.Index(fields=['case'], name='api_eligibi_case_id_2ba093_idx'), models.Index(fields=['eligible_status'], name='api_eligibi_eligibl_36f90b_idx')],
            },
        ),
    ]
