# Generated by Django 6.0.5 on 2026-06-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_assessment_screeningform_assessmentquestionnaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibility',
            name='responses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
