# Generated by Django 6.0.5 on 2026-06-03 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_eligibility_responses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eligibility',
            name='responses',
        ),
        migrations.AddField(
            model_name='answer',
            name='eligibility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.eligibility'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='screening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.screening'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['eligibility'], name='api_answer_eligibi_478fc1_idx'),
        ),
    ]
