# Generated by Django 6.0.5 on 2026-06-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_eligibility_responses_answer_eligibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='authorization_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='authorized_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='program_cap',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='service_authorization_status_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='case',
            name='social_care_coverage_plan',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='case',
            name='social_care_coverage_status',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='case',
            name='unite_us_authorization_id',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
