# Generated by Django 6.0.5 on 2026-06-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_case_authorization_note_case_authorized_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='authorized_amount',
            field=models.CharField(blank=True, default='', max_length=120),
            preserve_default=False,
        ),
    ]
