# Generated by Django 6.0.5 on 2026-06-05 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_case_authorized_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_offered', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(default='Unite Us', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_offered', 'is_active'], name='api_product_is_offe_4d0b89_idx')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('cooking_supplies', 'Cooking Supplies'), ('sow_development', 'SOW Development'), ('fresh_produce_groceries', 'Fresh Produce and Nonperishable Groceries'), ('home_accessibility', 'Home Accessibility'), ('home_remediation', 'Home Remediation'), ('mtna_food_rx_boxes', 'MTNA Food Prescription Boxes'), ('mtna_food_rx_voucher', 'MTNA Food Prescriptions Voucher'), ('nutritional_counseling_education', 'Nutritional Counseling and Education'), ('reauthorization', 'Reauthorization'), ('clinically_appropriate_meals', 'Clinically Appropriate Meals'), ('food_pantry', 'Food Pantry'), ('groceries_to_go', 'Groceries to Go'), ('health_home_adult_care', 'Health Home Adult Care'), ('housing_transition', 'Housing Transition'), ('medically_tailored_meals', 'Medically Tailored Meals (MTM)'), ('other', 'Other'), ('snap', 'SNAP'), ('tenancy', 'Tenancy'), ('transportation', 'Transportation'), ('none', 'None')], max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('is_offered', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='api.product')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_offered', 'is_active'], name='api_service_is_offe_6378ac_idx'), models.Index(fields=['product'], name='api_service_product_09c15a_idx')],
            },
        ),
    ]
