# Generated by Django 6.0.5 on 2026-06-05 18:12

from django.db import migrations


# Products we track. Today we only OFFER Food; others can be added later as we
# learn which products appear in screening results.
PRODUCTS = [
    {"code": "food", "name": "Food", "is_offered": True},
]

# Service types we currently offer, mapped to the product we deliver them under.
# Keyed by the ServiceType code. Everything else in the taxonomy is seeded as a
# tracked-but-not-offered service.
OFFERED_SERVICES = {
    "medically_tailored_meals": "food",
    "clinically_appropriate_meals": "food",
}


def seed(apps, schema_editor):
    Product = apps.get_model("api", "Product")
    Service = apps.get_model("api", "Service")
    # ServiceType lives in models as a TextChoices; import lazily so the
    # migration stays decoupled from app loading order.
    from api.models import ServiceType

    products_by_code = {}
    for p in PRODUCTS:
        obj, _ = Product.objects.update_or_create(
            code=p["code"],
            defaults={"name": p["name"], "is_offered": p["is_offered"]},
        )
        products_by_code[p["code"]] = obj

    for code, label in ServiceType.choices:
        product_code = OFFERED_SERVICES.get(code)
        is_offered = product_code is not None
        product = products_by_code.get(product_code) if product_code else None
        Service.objects.update_or_create(
            code=code,
            defaults={
                "name": label,
                "is_offered": is_offered,
                "product": product,
                "category": product.name if product else "",
            },
        )


def unseed(apps, schema_editor):
    Product = apps.get_model("api", "Product")
    Service = apps.get_model("api", "Service")
    Service.objects.all().delete()
    Product.objects.filter(code__in=[p["code"] for p in PRODUCTS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_product_service'),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
