# Generated by Django 6.0.5 on 2026-06-05 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_seed_product_service_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lifecycle_stage',
            field=models.CharField(choices=[('lead', 'Lead'), ('prospect', 'Prospect'), ('screened', 'Screened'), ('eligible', 'Eligible'), ('ineligible', 'Ineligible'), ('client', 'Client')], db_index=True, default='lead', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='lifecycle_stage_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('pending_validation', 'Pending Validation'), ('validated', 'Validated'), ('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('service_active', 'Service Active'), ('service_complete', 'Service Complete'), ('closed', 'Closed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], db_index=True, default='pending_validation', max_length=25)),
                ('stage_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='api.case')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='api.product')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(choices=[('validation', 'Validation'), ('verification', 'Verification')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('needs_followup', 'Needs Follow-up')], max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='api.enrollment')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_processes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadence', models.CharField(choices=[('once', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='once', max_length=20)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.enrollment')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='api.service')),
            ],
            options={
                'ordering': ['scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='StageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('client', 'Client'), ('enrollment', 'Enrollment')], db_index=True, max_length=20)),
                ('from_stage', models.CharField(blank=True, max_length=25)),
                ('to_stage', models.CharField(max_length=25)),
                ('source', models.CharField(choices=[('auto', 'Auto (derived)'), ('manual', 'Manual')], default='auto', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_events', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_events', to='api.client')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_events', to='api.enrollment')),
            ],
            options={
                'ordering': ['-entered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['client', 'stage'], name='api_enrollm_client__6b3767_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['product', 'stage'], name='api_enrollm_product_67ef7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('client', 'product'), name='unique_client_product_enrollment'),
        ),
        migrations.AddIndex(
            model_name='enrollmentprocess',
            index=models.Index(fields=['enrollment', 'process_type', 'status'], name='api_enrollm_enrollm_eb853b_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceschedule',
            index=models.Index(fields=['enrollment', 'status'], name='api_service_enrollm_19308a_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceschedule',
            index=models.Index(fields=['scheduled_start'], name='api_service_schedul_49abfb_idx'),
        ),
        migrations.AddIndex(
            model_name='stageevent',
            index=models.Index(fields=['entity_type', 'to_stage'], name='api_stageev_entity__38d07e_idx'),
        ),
        migrations.AddIndex(
            model_name='stageevent',
            index=models.Index(fields=['client', 'entered_at'], name='api_stageev_client__23fa9a_idx'),
        ),
        migrations.AddIndex(
            model_name='stageevent',
            index=models.Index(fields=['enrollment', 'entered_at'], name='api_stageev_enrollm_ed94c7_idx'),
        ),
    ]
