# Generated by Django 6.0.5 on 2026-06-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_client_lifecycle_stage_client_lifecycle_stage_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='crm_sync_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='client',
            name='crm_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
