# Generated by Django 6.0.5 on 2026-06-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_client_crm_sync_hash_client_crm_synced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='communication_channels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='client',
            name='preferred_communication_times',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='client',
            name='preferred_languages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
