# Generated by Django 6.0.5 on 2026-06-10 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_client_communication_channels_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractedService',
            fields=[
                ('contracted_service_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('service_type', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(blank=True, max_length=80)),
                ('fee_schedule_program_id', models.UUIDField(blank=True, null=True)),
                ('fee_schedule_program_name', models.CharField(blank=True, max_length=255)),
                ('unit_type', models.CharField(blank=True, max_length=80)),
                ('service_authorization_id', models.UUIDField(blank=True, null=True)),
                ('unite_us_authorization_id', models.CharField(blank=True, max_length=80)),
                ('authorization_status', models.CharField(blank=True, max_length=80)),
                ('authorized_amount', models.CharField(blank=True, max_length=120)),
                ('authorized_units', models.CharField(blank=True, max_length=80)),
                ('service_duration', models.CharField(blank=True, max_length=255)),
                ('service_starts_at', models.DateField(blank=True, null=True)),
                ('service_ends_at', models.DateField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=120)),
                ('invoice_status', models.CharField(blank=True, max_length=80)),
                ('invoice_amount', models.CharField(blank=True, max_length=120)),
                ('invoice_url', models.URLField(blank=True, max_length=1000)),
                ('invoiced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracted_services', to='api.case')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracted_services', to='api.importbatch')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['case'], name='api_contrac_case_id_09be9f_idx'), models.Index(fields=['service_authorization_id'], name='api_contrac_service_254369_idx')],
            },
        ),
    ]
