# Generated by Django 4.2.20 on 2026-06-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_contractedservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='crm_opportunity_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='case',
            name='crm_sync_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='case',
            name='crm_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='crm_source',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='client',
            name='doctors_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='doctors_fax',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='client',
            name='doctors_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='doctors_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='client',
            name='doctors_street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eligibility',
            name='crm_opportunity_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='eligibility',
            name='crm_sync_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='eligibility',
            name='crm_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='crm_opportunity_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='screening',
            name='crm_sync_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='screening',
            name='crm_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
