# Generated by Django 4.2.20 on 2026-06-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_case_crm_opportunity_id_case_crm_sync_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='screen_type',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
