# Generated by Django 4.2.20 on 2026-06-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_screening_type_freeform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='screen_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
