# Generated by Django 4.2.20 on 2026-06-11 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_import_agents'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agent',
            new_name='api_agent_agent_c_6f16c3_idx',
            old_name='api_agent_agent_c_8c91d6_idx',
        ),
        migrations.RenameIndex(
            model_name='agent',
            new_name='api_agent_group_5dac9a_idx',
            old_name='api_agent_group_s_6f9f68_idx',
        ),
    ]
