# Generated by Django 4.2.20 on 2026-06-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_api_agent_agent_c_8c91d6_idx_api_agent_agent_c_6f16c3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('current', 'Current'), ('home', 'Home'), ('work', 'Work'), ('mailing', 'Mailing'), ('delivery', 'Delivery'), ('temporary', 'Temporary')], default='current', max_length=20),
        ),
    ]
