# Generated by Django 4.2.20 on 2026-06-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_case_service_fields_length'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='programpipeline',
            new_name='api_program_case_ca_e515c4_idx',
            old_name='api_program_case_ca_idx',
        ),
        migrations.AddField(
            model_name='agent',
            name='calltools_app_user',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='calltools_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='agent',
            name='first_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='agent',
            name='is_account_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='is_agent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='last_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='agent',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
