# Generated by Django 4.2.20 on 2026-06-15 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_rename_api_program_case_ca_idx_api_program_case_ca_e515c4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('medicaid', 'Medicaid'), ('medicare', 'Medicare'), ('commercial', 'Commercial'), ('marketplace', 'Marketplace'), ('dual', 'Dual (Medicare/Medicaid)'), ('self_pay', 'Self Pay'), ('other', 'Other')], default='medicaid', max_length=20),
        ),
        migrations.CreateModel(
            name='SocialCareCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('plan_type', models.CharField(blank=True, choices=[('medicaid', 'Medicaid'), ('medicare', 'Medicare'), ('commercial', 'Commercial'), ('marketplace', 'Marketplace'), ('dual', 'Dual (Medicare/Medicaid)'), ('self_pay', 'Self Pay'), ('other', 'Other')], default='medicaid', max_length=20)),
                ('plan_name', models.CharField(blank=True, max_length=255)),
                ('external_member_id', models.CharField(blank=True, max_length=64)),
                ('external_group_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(blank=True, choices=[('enrolled', 'Enrolled'), ('non_enrolled', 'Non-Enrolled'), ('expired', 'Expired')], max_length=20)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ingested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_care_coverages', to='api.client')),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'indexes': [models.Index(fields=['client', 'status'], name='api_socialc_client__1276a1_idx'), models.Index(fields=['external_member_id'], name='api_socialc_externa_d1c1d8_idx')],
            },
        ),
    ]
