# Generated by Django 4.2.20 on 2026-06-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_insurance_plan_type_socialcarecoverage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentquestionnaire',
            name='assessment',
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='AssessmentQuestionnaire',
        ),
    ]
