# Generated by Django 4.2.20 on 2026-06-15 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_rename_eligibility_to_assessment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['-screen_created_at'], 'verbose_name_plural': 'assessments'},
        ),
        migrations.RemoveIndex(
            model_name='answer',
            name='api_answer_eligibi_478fc1_idx',
        ),
        migrations.RenameIndex(
            model_name='assessment',
            new_name='api_assessm_subject_9d7a20_idx',
            old_name='api_eligibi_subject_edf179_idx',
        ),
        migrations.RenameIndex(
            model_name='assessment',
            new_name='api_assessm_client__166504_idx',
            old_name='api_eligibi_client__8a8947_idx',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='api.client'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['assessment'], name='api_answer_assessm_bea454_idx'),
        ),
    ]
