# Generated by Django 4.2.20 on 2026-06-15 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_programmaincategory_service_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question_option',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='screening',
        ),
        migrations.RemoveField(
            model_name='importbatch',
            name='imported_by',
        ),
        migrations.RemoveField(
            model_name='question',
            name='parent_question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='template',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='screening',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='parent_question_option',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='question',
        ),
        migrations.RemoveField(
            model_name='screentemplate',
            name='parent_template',
        ),
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_client_product_enrollment',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='api_enrollm_product_67ef7c_idx',
        ),
        migrations.RemoveIndex(
            model_name='service',
            name='api_service_product_09c15a_idx',
        ),
        migrations.RemoveField(
            model_name='contractedservice',
            name='import_batch',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='service',
            name='product',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='ImportBatch',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Questionnaire',
        ),
        migrations.DeleteModel(
            name='QuestionOption',
        ),
        migrations.DeleteModel(
            name='ScreeningForm',
        ),
        migrations.DeleteModel(
            name='ScreenTemplate',
        ),
    ]
