# Generated by Django 4.2.20 on 2026-06-16 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0040_historicalcase_historicalclient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='product_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='renewal_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_number', models.PositiveSmallIntegerField(db_index=True, default=1)),
                ('event_type', models.CharField(choices=[('consent_granted', 'Consent Granted'), ('insurance', 'Insurance'), ('social_care_coverage', 'Social Care Coverage'), ('screening', 'Screening'), ('assessment', 'Assessment'), ('case_opened', 'Case'), ('verification', 'Verification'), ('enrolled', 'Enrolled')], db_index=True, max_length=30)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('badge_text', models.CharField(blank=True, max_length=120)),
                ('badge_tone', models.CharField(blank=True, choices=[('neutral', 'Neutral'), ('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')], default='neutral', max_length=10)),
                ('source', models.CharField(blank=True, db_index=True, max_length=20)),
                ('actor', models.CharField(blank=True, max_length=120)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='api.client')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to='api.enrollment')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['client', 'occurred_at'], name='api_timelin_client__365409_idx'), models.Index(fields=['event_type'], name='api_timelin_event_t_923c0b_idx'), models.Index(fields=['enrollment', 'renewal_number'], name='api_timelin_enrollm_34d67c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='timelineevent',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('dedupe_key',), name='unique_timeline_dedupe_key'),
        ),
    ]
