# Generated by Django 4.2.20 on 2026-06-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_enrollment_code_enrollment_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('navigation', 'Navigation'), ('external_service', 'External Service'), ('internal_service', 'Internal Service')], default='internal_service', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='household_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('household', 'Household')], default='individual', max_length=12),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='case_type',
            field=models.CharField(choices=[('navigation', 'Navigation'), ('external_service', 'External Service'), ('internal_service', 'Internal Service')], default='internal_service', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='household_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('household', 'Household')], default='individual', max_length=12),
        ),
    ]
