# Generated by Django 4.2.20 on 2026-06-16 19:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_case_case_type_case_household_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('household_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('relationship', models.CharField(blank=True, max_length=60)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='household_membership', to='api.client')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.household')),
            ],
            options={
                'ordering': ['-is_primary', 'added_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='householdmember',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('household',), name='unique_primary_per_household'),
        ),
    ]
