# Generated by Django 4.2.20 on 2026-06-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_household_householdmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_level',
            field=models.CharField(blank=True, choices=[('level_1', 'Level 1'), ('level_2', 'Level 2')], max_length=10),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='is_level',
            field=models.CharField(blank=True, choices=[('level_1', 'Level 1'), ('level_2', 'Level 2')], max_length=10),
        ),
    ]
