# Generated by Django 4.2.20 on 2026-06-17 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_rename_enrollment_to_enrollmentverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(blank=True, max_length=255)),
                ('dietary_restrictions', models.JSONField(blank=True, default=list)),
                ('food_allergies', models.JSONField(blank=True, default=list)),
                ('other_dietary_restrictions', models.TextField(blank=True)),
                ('meal_category', models.CharField(blank=True, choices=[('fresh_meal', 'Fresh Meal'), ('dairy_free', 'Dairy Free'), ('fish_free', 'Fish Free'), ('vegetarian', 'Vegetarian')], max_length=20)),
                ('menu_type', models.CharField(blank=True, choices=[('standard', 'Standard'), ('fish_free', 'Fish Free'), ('vegetarian', 'Vegetarian'), ('dairy_free', 'Dairy Free')], max_length=20)),
                ('general_verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='enrollmentverification',
            new_name='api_enrollm_client__50c2c9_idx',
            old_name='api_enrollm_client__6b3767_idx',
        ),
        migrations.AddField(
            model_name='enrollmentverification',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_verifications', to='api.address'),
        ),
        migrations.AddField(
            model_name='enrollmentverification',
            name='delivery_address_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentverification',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_verifications', to='api.household'),
        ),
        migrations.AddField(
            model_name='enrollmentverification',
            name='household_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentverification',
            name='is_family_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentverification',
            name='medicaid_type_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentverification',
            name='stage',
            field=models.CharField(choices=[('pending_validation', 'Pending Validation'), ('validated', 'Validated'), ('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('waiting_authorization', 'Waiting Authorization'), ('authorized', 'Authorized'), ('denied', 'Denied'), ('service_active', 'Service Active'), ('service_complete', 'Service Complete'), ('closed', 'Closed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], db_index=True, default='pending_verification', max_length=25),
        ),
        migrations.AddIndex(
            model_name='enrollmentverification',
            index=models.Index(fields=['household', 'stage'], name='api_enrollm_househo_b673d8_idx'),
        ),
        migrations.AddField(
            model_name='memberverification',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_verifications', to='api.client'),
        ),
        migrations.AddField(
            model_name='memberverification',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_verifications', to='api.enrollmentverification'),
        ),
        migrations.AddIndex(
            model_name='memberverification',
            index=models.Index(fields=['enrollment'], name='api_memberv_enrollm_c906a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='memberverification',
            constraint=models.UniqueConstraint(fields=('enrollment', 'client'), name='uniq_member_verification_per_enrollment_client'),
        ),
    ]
