# Generated by Django 4.2.20 on 2026-06-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_memberverification_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enrollmentverification',
            constraint=models.UniqueConstraint(condition=models.Q(('case__isnull', False)), fields=('case',), name='uniq_enrollment_verification_per_case'),
        ),
    ]
