# Generated by Django 4.2.20 on 2026-06-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_enrollmentverification_uniq_enrollment_verification_per_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentverification',
            name='stage',
            field=models.CharField(choices=[('pending_validation', 'Pending Validation'), ('validated', 'Validated'), ('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('waiting_authorization', 'Waiting Authorization'), ('authorized', 'Accepted'), ('denied', 'Denied'), ('service_active', 'Service Active'), ('service_complete', 'Service Complete'), ('closed', 'Closed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], db_index=True, default='pending_verification', max_length=25),
        ),
    ]
