# Generated by Django 4.2.20 on 2026-06-17 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0048_alter_enrollmentverification_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSchedule',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('program_name', models.CharField(blank=True, max_length=255)),
                ('member_name', models.CharField(blank=True, max_length=255)),
                ('anticipated_delivery_date', models.DateField(blank=True, null=True)),
                ('sent_to_kitchen_id', models.CharField(blank=True, max_length=120)),
                ('sent_to_delivery_company_id', models.CharField(blank=True, max_length=120)),
                ('household_group_code', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('on_the_kitchen', 'On the Kitchen'), ('on_the_way', 'On the Way'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20)),
                ('delivery_address', models.TextField(blank=True)),
                ('address_notes', models.TextField(blank=True)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('restrictions', models.JSONField(blank=True, default=list)),
                ('menu_type', models.CharField(blank=True, choices=[('standard', 'Standard'), ('fish_free', 'Fish Free'), ('vegetarian', 'Vegetarian'), ('dairy_free', 'Dairy Free')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('member_phone', models.CharField(blank=True, max_length=40)),
                ('member_email', models.EmailField(blank=True, max_length=254)),
                ('how_many_meals_or_boxes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.enrollmentverification')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='api.household')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.memberverification')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderDeliveryProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_key', models.CharField(max_length=500)),
                ('file_url', models.URLField(blank=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='api.orderschedule')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_delivery_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='orderschedule',
            index=models.Index(fields=['enrollment', 'status'], name='api_ordersc_enrollm_068c14_idx'),
        ),
        migrations.AddIndex(
            model_name='orderschedule',
            index=models.Index(fields=['household_group_code'], name='api_ordersc_househo_591689_idx'),
        ),
        migrations.AddIndex(
            model_name='orderschedule',
            index=models.Index(fields=['status'], name='api_ordersc_status_b05595_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdeliveryproof',
            index=models.Index(fields=['order'], name='api_orderde_order_i_c97638_idx'),
        ),
    ]
