# Generated by Django 4.2.20 on 2026-06-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_orderschedule_orderdeliveryproof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentverification',
            name='service_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
