# Generated by Django 4.2.20 on 2026-06-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_enrollmentverification_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentverification',
            name='delivery_weekdays',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='memberverification',
            name='denied_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='memberverification',
            name='meals_per_delivery',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberverification',
            name='status',
            field=models.CharField(choices=[('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('denied', 'Denied')], db_index=True, default='pending_verification', max_length=25),
        ),
    ]
