# Generated by Django 4.2.20 on 2026-06-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_enrollmentverification_delivery_weekdays_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('borough', models.CharField(blank=True, max_length=255)),
                ('scn', models.CharField(blank=True, max_length=120)),
                ('platform', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['zip_code'],
            },
        ),
        migrations.AddField(
            model_name='enrollmentverification',
            name='call_transfer_answered',
            field=models.CharField(blank=True, choices=[('transfer_successful', 'Transfer Successful (Verification Agent Answered)'), ('transfer_failed', 'Transfer Failed (No Answer)'), ('no_verification_needed', 'No Verification Needed')], max_length=30),
        ),
    ]
