# Generated by Django 4.2.20 on 2026-06-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_allowedzipcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lifecycle_stage',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('consent', 'Consent'), ('screened', 'Screened'), ('assessment', 'Assessment'), ('navigation', 'Navigation'), ('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('waiting_authorization', 'Waiting Authorization'), ('authorized', 'Authorized'), ('active', 'Active'), ('completed', 'Completed'), ('not_eligible', 'Not Eligible')], db_index=True, default='inactive', max_length=25),
        ),
        migrations.AddField(
            model_name='client',
            name='lifecycle_stage_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='lifecycle_stage',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('consent', 'Consent'), ('screened', 'Screened'), ('assessment', 'Assessment'), ('navigation', 'Navigation'), ('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('waiting_authorization', 'Waiting Authorization'), ('authorized', 'Authorized'), ('active', 'Active'), ('completed', 'Completed'), ('not_eligible', 'Not Eligible')], db_index=True, default='inactive', max_length=25),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='lifecycle_stage_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
