# Generated by Django 4.2.20 on 2026-06-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_client_lifecycle_stage_client_lifecycle_stage_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('navigation', 'Navigation'), ('external_service', 'External Service'), ('internal_service', 'Internal Service'), ('eligibility', 'Eligibility')], default='internal_service', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='case_type',
            field=models.CharField(choices=[('navigation', 'Navigation'), ('external_service', 'External Service'), ('internal_service', 'Internal Service'), ('eligibility', 'Eligibility')], default='internal_service', max_length=20),
        ),
    ]
