# Generated by Django 4.2.20 on 2026-06-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_agentlogincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='department',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='agent',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
