# Generated by Django 4.2.20 on 2026-06-19 17:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_agent_department_agent_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryTag',
            fields=[
                ('dietary_tag_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('type', models.CharField(choices=[('restriction', 'Restriction'), ('allergy', 'Allergy')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuType',
            fields=[
                ('menu_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuTypeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dietary_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_type_tags', to='api.dietarytag')),
                ('menu_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_type_tags', to='api.menutype')),
            ],
        ),
        migrations.AddField(
            model_name='menutype',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='menu_types', through='api.MenuTypeTag', to='api.dietarytag'),
        ),
        migrations.AddIndex(
            model_name='dietarytag',
            index=models.Index(fields=['type'], name='api_dietary_type_041ba8_idx'),
        ),
        migrations.AddIndex(
            model_name='menutypetag',
            index=models.Index(fields=['menu_type'], name='api_menutyp_menu_ty_44815f_idx'),
        ),
        migrations.AddIndex(
            model_name='menutypetag',
            index=models.Index(fields=['dietary_tag'], name='api_menutyp_dietary_688d75_idx'),
        ),
        migrations.AddConstraint(
            model_name='menutypetag',
            constraint=models.UniqueConstraint(fields=('menu_type', 'dietary_tag'), name='uniq_menu_type_dietary_tag'),
        ),
    ]
