# Generated by Django 4.2.20 on 2026-06-19 17:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_dietarytag_menutype_menutypetag_menutype_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('kitchen_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('max_orders_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KitchenMenuType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_menu_types', to='api.kitchen')),
                ('menu_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_menu_types', to='api.menutype')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenIntegration',
            fields=[
                ('kitchen_integration_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('email', 'Email'), ('api', 'API')], max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='api.kitchen')),
            ],
            options={
                'ordering': ['kitchen', 'method'],
            },
        ),
        migrations.AddField(
            model_name='kitchen',
            name='menu_types',
            field=models.ManyToManyField(blank=True, related_name='kitchens', through='api.KitchenMenuType', to='api.menutype'),
        ),
        migrations.AddIndex(
            model_name='kitchenmenutype',
            index=models.Index(fields=['kitchen'], name='api_kitchen_kitchen_178717_idx'),
        ),
        migrations.AddIndex(
            model_name='kitchenmenutype',
            index=models.Index(fields=['menu_type'], name='api_kitchen_menu_ty_6bc147_idx'),
        ),
        migrations.AddConstraint(
            model_name='kitchenmenutype',
            constraint=models.UniqueConstraint(fields=('kitchen', 'menu_type'), name='uniq_kitchen_menu_type'),
        ),
        migrations.AddIndex(
            model_name='kitchenintegration',
            index=models.Index(fields=['kitchen'], name='api_kitchen_kitchen_1a9ee1_idx'),
        ),
        migrations.AddConstraint(
            model_name='kitchenintegration',
            constraint=models.UniqueConstraint(fields=('kitchen', 'method'), name='uniq_kitchen_integration_method'),
        ),
        migrations.AddIndex(
            model_name='kitchen',
            index=models.Index(fields=['status'], name='api_kitchen_status_5ebc08_idx'),
        ),
    ]
