# Generated by Django 4.2.20 on 2026-06-19 17:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_kitchen_kitchenmenutype_kitchenintegration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCompany',
            fields=[
                ('delivery_company_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'delivery companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryCompanyIntegration',
            fields=[
                ('delivery_company_integration_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('email', 'Email'), ('api', 'API')], max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='api.deliverycompany')),
            ],
            options={
                'ordering': ['delivery_company', '-is_primary', 'method'],
            },
        ),
        migrations.AddIndex(
            model_name='deliverycompany',
            index=models.Index(fields=['status'], name='api_deliver_status_516d95_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverycompanyintegration',
            index=models.Index(fields=['delivery_company'], name='api_deliver_deliver_7aa559_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliverycompanyintegration',
            constraint=models.UniqueConstraint(fields=('delivery_company', 'method'), name='uniq_delivery_company_integration_method'),
        ),
        migrations.AddConstraint(
            model_name='deliverycompanyintegration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('delivery_company',), name='uniq_primary_delivery_company_integration'),
        ),
    ]
