# Generated by Django 4.2.20 on 2026-06-19 17:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_deliverycompany_deliverycompanyintegration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('purchase_order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('kitchen_status', models.CharField(choices=[('not_sent', 'Not Sent'), ('sent_to_kitchen', 'Sent to Kitchen'), ('accepted_by_kitchen', 'Accepted by Kitchen'), ('in_preparation', 'In Preparation'), ('ready_for_dispatch', 'Ready for Dispatch')], default='not_sent', max_length=30)),
                ('delivery_status', models.CharField(choices=[('not_sent', 'Not Sent'), ('sent_to_delivery', 'Sent to Delivery'), ('accepted_by_delivery', 'Accepted by Delivery'), ('out_for_delivery', 'Out for Delivery'), ('completed', 'Completed'), ('partially_completed', 'Partially Completed')], default='not_sent', max_length=30)),
                ('sent_to_kitchen_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='api.deliverycompany')),
                ('kitchen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='api.kitchen')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('delivery_order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready_for_delivery', 'Ready for Delivery'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('returned', 'Returned')], default='pending', max_length=30)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('proof_of_delivery', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_dietary_tags', models.ManyToManyField(blank=True, related_name='delivery_orders', to='api.dietarytag')),
                ('delivery_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='api.deliverycompany')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='api.household')),
                ('kitchen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='api.kitchen')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='api.client')),
                ('menu_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='api.menutype')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='api.purchaseorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='api_purchas_status_75cb5d_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['delivery_date'], name='api_purchas_deliver_21d1b1_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['kitchen', 'status'], name='api_purchas_kitchen_28a51d_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryorder',
            index=models.Index(fields=['purchase_order'], name='api_deliver_purchas_b31d24_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryorder',
            index=models.Index(fields=['status'], name='api_deliver_status_898c52_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryorder',
            index=models.Index(fields=['member'], name='api_deliver_member__55afb0_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryorder',
            index=models.Index(fields=['expected_delivery_date'], name='api_deliver_expecte_1179ee_idx'),
        ),
    ]
