# Generated by Django 4.2.20 on 2026-06-19 20:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_purchaseorder_deliveryorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPhone',
            fields=[
                ('client_phone_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw', models.CharField(max_length=40)),
                ('normalized', models.CharField(db_index=True, max_length=20)),
                ('label', models.CharField(blank=True, max_length=20)),
                ('source', models.CharField(choices=[('uniteus', 'Unite Us'), ('calltools', 'CallTools'), ('agent', 'Agent')], default='agent', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='api.client')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
                'indexes': [models.Index(fields=['normalized'], name='api_clientp_normali_c2d3db_idx'), models.Index(fields=['client', 'is_primary'], name='api_clientp_client__f5c1b9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='clientphone',
            constraint=models.UniqueConstraint(fields=('client', 'normalized'), name='uniq_client_phone_normalized'),
        ),
    ]
