# Generated by Django 4.2.20 on 2026-06-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_menutype_is_active_ticketnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentlogincode',
            name='source',
            field=models.CharField(choices=[('extension', 'Extension'), ('portal', 'Support portal')], db_index=True, default='extension', max_length=20),
        ),
    ]
