# Generated by Django 4.2.20 on 2026-06-21 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_agentlogincode_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('lead_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(db_index=True, max_length=32)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('zip_code', models.CharField(max_length=10)),
                ('medicaid_enrollment', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_sure', 'Not sure')], max_length=10)),
                ('disclaimer_accepted', models.BooleanField(default=False)),
                ('disclaimer_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('medicaid_id', models.CharField(blank=True, max_length=60)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('additional_details', models.TextField(blank=True)),
                ('household_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('preferred_contact_method', models.CharField(blank=True, choices=[('phone', 'Phone'), ('text', 'Text'), ('email', 'Email')], max_length=10)),
                ('do_not_contact', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('disqualified', 'Disqualified')], db_index=True, default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='api_lead_status_bda661_idx')],
            },
        ),
    ]
