# Generated by Django 4.2.20 on 2026-06-22 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_householdmember_mobile_app_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='eligibility_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='program',
            name='eligibility_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ProgramEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligibility_score', models.FloatField(blank=True, null=True)),
                ('is_eligible', models.BooleanField(default=False)),
                ('model_version', models.CharField(blank=True, max_length=60)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_eligibilities', to='api.householdmember')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibilities', to='api.program')),
            ],
            options={
                'verbose_name_plural': 'program eligibilities',
                'ordering': ['-evaluated_at'],
                'indexes': [models.Index(fields=['member', 'program'], name='api_program_member__685e70_idx'), models.Index(fields=['program', 'is_eligible'], name='api_program_program_b857a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProgramDisplayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayed_at', models.DateTimeField(auto_now_add=True)),
                ('clicked', models.BooleanField(default=False)),
                ('applied', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_display_logs', to='api.householdmember')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_logs', to='api.program')),
            ],
            options={
                'ordering': ['-displayed_at'],
                'indexes': [models.Index(fields=['member', 'program'], name='api_program_member__179782_idx'), models.Index(fields=['program', 'displayed_at'], name='api_program_program_114f56_idx')],
            },
        ),
    ]
