# Generated by Django 4.2.20 on 2026-06-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_lead_assigned_to_lead_converted_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='interested_programs',
            field=models.ManyToManyField(blank=True, related_name='interested_leads', to='api.programmaincategory'),
        ),
    ]
