# Generated by Django 4.2.20 on 2026-06-22 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_lead_interested_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('attempting_contact', 'Attempting to Contact'), ('contacted', 'Contacted'), ('enrolled', 'Enrolled'), ('not_eligible', 'Not Eligible'), ('closed', 'Close'), ('lost', 'Lost')], db_index=True, default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_notes', to='api.agent')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
