# Generated by Django 4.2.20 on 2026-06-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_alter_lead_status_leadnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='supported_products',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='kitchenmenutype',
            name='menu_type_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='kitchenmenutype',
            name='restrictions',
            field=models.ManyToManyField(blank=True, related_name='kitchen_menu_type_restrictions', to='api.dietarytag'),
        ),
    ]
