# Generated by Django 4.2.20 on 2026-06-23 16:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_kitchen_supported_products_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('product_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('meals', 'Meals'), ('boxes', 'Boxes')], max_length=20, unique=True)),
                ('prod_per_delivery', models.PositiveIntegerField(default=0)),
                ('delivery_days_cadence', models.CharField(blank=True, choices=[('mon_thu', 'Mon/Thu'), ('tue_fri', 'Tue/Fri'), ('once_a_week', 'Once a Week')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['type'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='api.producttype'),
        ),
    ]
