# Generated by Django 4.2.20 on 2026-06-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_seed_product_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['type', 'delivery_days_cadence']},
        ),
        migrations.AlterField(
            model_name='producttype',
            name='type',
            field=models.CharField(choices=[('meals', 'Meals'), ('boxes', 'Boxes')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='producttype',
            constraint=models.UniqueConstraint(fields=('type', 'delivery_days_cadence'), name='uniq_product_type_type_cadence'),
        ),
    ]
