# Generated by Django 4.2.20 on 2026-06-23 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_alter_producttype_options_alter_producttype_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberDeliverySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(blank=True, max_length=255)),
                ('delivery_days_cadence', models.CharField(blank=True, choices=[('mon_thu', 'Mon/Thu'), ('tue_fri', 'Tue/Fri'), ('once_a_week', 'Once a Week')], max_length=20)),
                ('prod_per_delivery', models.PositiveSmallIntegerField(default=0)),
                ('meals_boxes_total', models.PositiveIntegerField(default=0)),
                ('menu_type', models.CharField(blank=True, choices=[('standard', 'Standard'), ('fish_free', 'Fish Free'), ('vegetarian', 'Vegetarian'), ('dairy_free', 'Dairy Free')], max_length=20)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], db_index=True, default='scheduled', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_schedules', to='api.enrollmentverification')),
                ('household_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_schedules', to='api.householdmember')),
                ('member_verification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_schedules', to='api.memberverification')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_schedules', to='api.producttype')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_schedules', to='api.program')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['enrollment', 'status'], name='api_memberd_enrollm_cf7b77_idx'), models.Index(fields=['household_member'], name='api_memberd_househo_60eca8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='memberdeliveryschedule',
            constraint=models.UniqueConstraint(fields=('enrollment', 'household_member', 'product_type'), name='uniq_member_delivery_schedule'),
        ),
    ]
