# Generated by Django 4.2.20 on 2026-06-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_memberdeliveryschedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_kind', models.CharField(choices=[('meals', 'Meals'), ('boxes', 'Boxes')], max_length=20)),
                ('accepted_weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Weekday the case authorization is accepted (becomes active).')),
                ('cadence', models.CharField(choices=[('mon_thu', 'Mon/Thu'), ('tue_fri', 'Tue/Fri'), ('once_a_week', 'Once a Week')], max_length=20)),
                ('delivery_weekdays', models.JSONField(blank=True, default=list, help_text='Weekdays deliveries land on, e.g. ["mon", "thu"].')),
                ('po_weekdays', models.JSONField(blank=True, default=list, help_text='Weekdays purchase orders are generated, e.g. ["tue", "fri"].')),
                ('first_delivery_weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Weekday of the first delivery (the next delivery day after activation).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['product_kind', 'accepted_weekday'],
            },
        ),
        migrations.AddConstraint(
            model_name='cadencerule',
            constraint=models.UniqueConstraint(fields=('product_kind', 'accepted_weekday'), name='uniq_cadence_rule_kind_weekday'),
        ),
    ]
