# Generated by Django 4.2.20 on 2026-06-23 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_rename_memberverification_memberdietaryprofile'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='memberdietaryprofile',
            new_name='api_memberd_enrollm_70349f_idx',
            old_name='api_memberv_enrollm_c906a6_idx',
        ),
    ]
