# Generated by Django 4.2.20 on 2026-06-24 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_add_kitchen_assignment_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentverification',
            name='kitchen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_verifications', to='api.kitchen'),
        ),
        migrations.AddField(
            model_name='memberdeliveryschedule',
            name='kitchen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_schedules', to='api.kitchen'),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='lifecycle_stage',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('consent', 'Consent'), ('screened', 'Screened'), ('assessment', 'Assessment'), ('navigation', 'Navigation'), ('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('waiting_authorization', 'Waiting Authorization'), ('authorized', 'Authorized'), ('kitchen_assignment', 'Kitchen Assignment'), ('active', 'Active'), ('completed', 'Completed'), ('not_eligible', 'Not Eligible')], db_index=True, default='inactive', max_length=25),
        ),
    ]
