# Generated by Django 4.2.20 on 2026-06-24 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_enrollmentverification_kitchen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='default_kitchen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_delivery_orders', to='api.kitchen'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='rerouted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderschedule',
            name='kitchen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_schedules', to='api.kitchen'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='kind',
            field=models.CharField(blank=True, choices=[('meals', 'Meals'), ('boxes', 'Boxes')], max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='po_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='api.producttype'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='split_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='splits', to='api.purchaseorder'),
        ),
    ]
