# Generated by Django 4.2.20 on 2026-06-24 18:56

from django.db import migrations, models


def backfill_quantity(apps, schema_editor):
    """Populate quantity on existing DeliveryOrders from the source
    OrderSchedule (matched by member client + delivery date + household)."""
    DeliveryOrder = apps.get_model('api', 'DeliveryOrder')
    OrderSchedule = apps.get_model('api', 'OrderSchedule')
    for do in DeliveryOrder.objects.filter(quantity__isnull=True):
        sched = (
            OrderSchedule.objects.filter(
                member__client=do.member_id,
                anticipated_delivery_date=do.expected_delivery_date,
                household=do.group_id,
            )
            .exclude(how_many_meals_or_boxes__isnull=True)
            .first()
        )
        if sched is not None:
            do.quantity = sched.how_many_meals_or_boxes
            do.save(update_fields=['quantity'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_realign_cadence_po_weekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_quantity, noop),
    ]
