# Generated by Django 4.2.20 on 2026-06-24 19:27

from datetime import timedelta

from django.db import migrations, models

_WEEKDAY_CODES = {
    "mon": 0, "tue": 1, "wed": 2, "thu": 3, "fri": 4, "sat": 5, "sun": 6,
}
# Fallback weekday ints when an enrollment has no explicit delivery_weekdays.
_CADENCE_WEEKDAYS = {"mon_thu": [0, 3], "tue_fri": [1, 4]}


def _coverage(weekday, ints):
    """Days a delivery on ``weekday`` covers (cyclic gap to next delivery)."""
    days = sorted(set(ints))
    if not days or weekday not in days:
        return 7
    i = days.index(weekday)
    nxt = days[(i + 1) % len(days)]
    return (nxt - weekday) % 7 or 7


def _delivery_dates(start, end, ints):
    wanted = set(ints)
    if not wanted or not start or not end or end < start:
        return []
    out, d = [], start
    while d <= end:
        if d.weekday() in wanted:
            out.append(d)
        d += timedelta(days=1)
    return out


def _weekday_ints_for(enrollment, cadence):
    ints = [
        _WEEKDAY_CODES[w]
        for w in (getattr(enrollment, "delivery_weekdays", None) or [])
        if w in _WEEKDAY_CODES
    ]
    return ints or _CADENCE_WEEKDAYS.get(cadence, [])


def backfill_meals_per_day(apps, schema_editor):
    """Treat the existing meals ProductType.prod_per_delivery as the daily rate,
    snapshot it onto meals plans, and recompute meals quantities/totals so the
    delivery calendar reflects the per-delivery coverage (e.g. 9 then 12)."""
    ProductType = apps.get_model("api", "ProductType")
    MemberDeliverySchedule = apps.get_model("api", "MemberDeliverySchedule")
    OrderSchedule = apps.get_model("api", "OrderSchedule")

    # 1) ProductType (meals): daily rate seeded from the old per-delivery value.
    for pt in ProductType.objects.filter(type="meals"):
        pt.meals_per_day = pt.prod_per_delivery or 0
        pt.save(update_fields=["meals_per_day"])

    # 2) Meals plans: snapshot meals_per_day and recompute the window total.
    for s in MemberDeliverySchedule.objects.select_related(
        "product_type", "enrollment"
    ):
        if not (s.product_type and s.product_type.type == "meals"):
            continue
        rate = s.product_type.meals_per_day or s.prod_per_delivery or 0
        s.meals_per_day = rate
        ints = _weekday_ints_for(s.enrollment, s.delivery_days_cadence)
        dates = _delivery_dates(s.starts_on, s.ends_on, ints)
        s.meals_boxes_total = sum(rate * _coverage(d.weekday(), ints) for d in dates)
        s.save(update_fields=["meals_per_day", "meals_boxes_total"])

    # 3) Existing meals OrderSchedule occurrences: set per-delivery coverage qty.
    for o in OrderSchedule.objects.select_related("enrollment"):
        plan = MemberDeliverySchedule.objects.filter(
            enrollment=o.enrollment, product_type__type="meals"
        ).first()
        if not plan or not plan.meals_per_day or not o.anticipated_delivery_date:
            continue
        ints = _weekday_ints_for(o.enrollment, plan.delivery_days_cadence)
        o.how_many_meals_or_boxes = plan.meals_per_day * _coverage(
            o.anticipated_delivery_date.weekday(), ints
        )
        o.save(update_fields=["how_many_meals_or_boxes"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_deliveryorder_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdeliveryschedule',
            name='meals_per_day',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producttype',
            name='meals_per_day',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(backfill_meals_per_day, noop),
    ]
