# Generated by Django 4.2.20 on 2026-06-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_resync_deliveryorder_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(choices=[('consent_granted', 'Consent Granted'), ('insurance', 'Insurance'), ('social_care_coverage', 'Social Care Coverage'), ('screening', 'Screening'), ('assessment', 'Assessment'), ('case_opened', 'Case'), ('verification', 'Verification'), ('enrolled', 'Enrolled'), ('service', 'Service')], db_index=True, max_length=30),
        ),
    ]
