# Generated by Django 4.2.20 on 2026-06-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_alter_timelineevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='source',
            field=models.CharField(blank=True, choices=[('live_call', 'Live Call'), ('call_back', 'Call Back'), ('assigned_ticket', 'Assigned Ticket'), ('delivery_issue', 'Delivery Issue'), ('email', 'Email'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='source',
            field=models.CharField(blank=True, choices=[('live_call', 'Live Call'), ('call_back', 'Call Back'), ('assigned_ticket', 'Assigned Ticket'), ('delivery_issue', 'Delivery Issue'), ('email', 'Email'), ('other', 'Other')], default='', max_length=20),
        ),
    ]
