# Generated by Django 4.2.20 on 2026-06-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_remap_legacy_timeline_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='kitchen_food_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='kitchen_meal_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='memberdeliveryschedule',
            name='kitchen_food_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='memberdeliveryschedule',
            name='kitchen_meal_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='memberdietaryprofile',
            name='kitchen_food_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='memberdietaryprofile',
            name='kitchen_meal_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='memberdietaryprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('out_of_orbit', 'Out of Orbit')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='orderschedule',
            name='kitchen_food_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderschedule',
            name='kitchen_meal_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='memberdeliveryschedule',
            name='menu_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='memberdietaryprofile',
            name='menu_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='orderschedule',
            name='menu_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(choices=[('consent_granted', 'Consent Granted'), ('insurance', 'Insurance'), ('social_care_coverage', 'Social Care Coverage'), ('screening', 'Screening'), ('assessment', 'Assessment'), ('case_opened', 'Case'), ('pending_validation', 'Pending Validation'), ('validated', 'Validated'), ('verification_requested', 'Verification Requested'), ('verification_completed', 'Verification Completed'), ('waiting_authorization', 'Waiting Authorization'), ('authorized', 'Authorized'), ('denied', 'Denied'), ('kitchen_assigned', 'Kitchen Assigned'), ('service_activated', 'Service Activated'), ('service_on_hold', 'Service On Hold'), ('service_resumed', 'Service Resumed'), ('service_completed', 'Service Completed'), ('service_closed', 'Service Closed'), ('service_cancelled', 'Service Cancelled'), ('enrolled', 'Enrolled'), ('ticket_created', 'New Ticket Created'), ('delivery_address_changed', 'Delivery Address Changed'), ('out_of_orbit', 'Out of Orbit'), ('verification', 'Verification'), ('service', 'Service')], db_index=True, max_length=30),
        ),
    ]
