# Generated by Django 4.2.20 on 2026-06-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_member_menu_type_codes_to_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='county',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='client',
            name='adults_in_household',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='care_coordinator',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='care_coordinator_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='children_in_household',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='citizenship',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='client',
            name='gross_monthly_income',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='client',
            name='middle_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='adults_in_household',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='care_coordinator',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='care_coordinator_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='children_in_household',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='citizenship',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='gross_monthly_income',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='middle_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
