# Generated by Django 4.2.20 on 2026-06-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_address_county_client_adults_in_household_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='form_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
