# Generated by Django 4.2.20 on 2026-06-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_assessment_form_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(choices=[('consent_granted', 'Consent Granted'), ('insurance', 'Insurance'), ('social_care_coverage', 'Social Care Coverage'), ('screening', 'Screening'), ('assessment', 'Assessment'), ('case_opened', 'Case'), ('pending_validation', 'Pending Validation'), ('validated', 'Validated'), ('verification_requested', 'Verification Requested'), ('verification_completed', 'Verification Completed'), ('waiting_authorization', 'Waiting Authorization'), ('authorized', 'Authorized'), ('denied', 'Denied'), ('kitchen_assigned', 'Kitchen Assigned'), ('service_activated', 'Service Activated'), ('service_on_hold', 'Service On Hold'), ('service_resumed', 'Service Resumed'), ('service_completed', 'Service Completed'), ('service_closed', 'Service Closed'), ('service_cancelled', 'Service Cancelled'), ('enrolled', 'Enrolled'), ('ticket_created', 'New Ticket Created'), ('delivery_address_changed', 'Delivery Address Changed'), ('out_of_orbit', 'Out of Orbit'), ('member_reactivated', 'Member Reactivated'), ('verification', 'Verification'), ('service', 'Service')], db_index=True, max_length=30),
        ),
    ]
