# Generated by Django 4.2.20 on 2026-06-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_alter_timelineevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='group',
            field=models.CharField(choices=[('Screeners', 'Screeners'), ('Verifiers', 'Verifiers'), ('Logistics', 'Logistics'), ('Management', 'Management'), ('CS', 'CS')], default='Screeners', max_length=50),
        ),
    ]
