# Generated by Django 4.2.20 on 2026-06-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_ticket_type_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='unit',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
