# Generated by Django 4.2.20 on 2026-06-30 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_address_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentverification',
            name='verified_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentverification',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_enrollments', to='api.agent'),
        ),
        migrations.AlterField(
            model_name='client',
            name='lifecycle_stage',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('consent', 'Consent'), ('screened', 'Screened'), ('assessment', 'Assessment'), ('navigation', 'Navigation'), ('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('kitchen_assignment', 'Kitchen Assignment'), ('active', 'Active'), ('completed', 'Completed'), ('not_eligible', 'Not Eligible')], db_index=True, default='inactive', max_length=25),
        ),
        migrations.AlterField(
            model_name='enrollmentverification',
            name='stage',
            field=models.CharField(choices=[('pending_validation', 'Pending Validation'), ('validated', 'Validated'), ('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('kitchen_assignment', 'Kitchen Assignment'), ('service_active', 'Service Active'), ('service_complete', 'Service Complete'), ('closed', 'Closed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], db_index=True, default='pending_verification', max_length=25),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='lifecycle_stage',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('consent', 'Consent'), ('screened', 'Screened'), ('assessment', 'Assessment'), ('navigation', 'Navigation'), ('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('kitchen_assignment', 'Kitchen Assignment'), ('active', 'Active'), ('completed', 'Completed'), ('not_eligible', 'Not Eligible')], db_index=True, default='inactive', max_length=25),
        ),
    ]
