# Generated by Django 4.2.20 on 2026-06-30 19:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_seed_meals_cadences'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniteUsAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, unique=True)),
                ('employee_id', models.UUIDField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('work_title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unite Us agent',
                'verbose_name_plural': 'Unite Us agents',
                'ordering': ['name'],
            },
        ),
    ]
