# Generated by Django 4.2.20 on 2026-06-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_uniteusagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniteusagent',
            name='is_us',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uniteusagent',
            name='originating_team',
            field=models.CharField(blank=True, default='Met Council Team', max_length=120),
        ),
    ]
