# Generated by Django 4.2.20 on 2026-06-30 22:35

from django.db import migrations, models


def backfill_is_williamsburg(apps, schema_editor):
    """Set the flag on existing clients whose lead_source is 'Williamsburg'."""
    Client = apps.get_model('api', 'Client')
    Client.objects.filter(lead_source__iexact='williamsburg').update(
        is_williamsburg=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_seed_unite_us_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_williamsburg',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='is_williamsburg',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(
            backfill_is_williamsburg, migrations.RunPython.noop
        ),
    ]
