# Generated by Django 4.2.20 on 2026-07-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_client_is_williamsburg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='service_authorization_requested_amount',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='service_authorization_requested_amount',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
