# Generated by Django 4.2.20 on 2026-07-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_alter_timelineevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrun',
            name='export_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='importrun',
            name='file_key',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='importrun',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='importrun',
            name='progress_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
