# Generated by Django 4.2.20 on 2026-07-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_importrun_export_type_importrun_file_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrun',
            name='planned_actions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
