# Generated by Django 4.2.20 on 2026-07-06 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_timelineevent_case_alter_timelineevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentverification',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_enrollments', to='api.agent'),
        ),
    ]
