# Generated by Django 4.2.20 on 2026-07-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_alter_memberdietaryprofile_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdietaryprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('out_of_orbit', 'Out of Orbit'), ('paused', 'Paused'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20),
        ),
    ]
