# Generated by Django 4.2.20 on 2026-07-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_alter_memberdietaryprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentverification',
            name='requested_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
