# Generated by Django 4.2.20 on 2026-07-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_enrollmentverification_requested_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludedZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.CharField(db_index=True, max_length=5, unique=True)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Excluded ZIP code',
                'verbose_name_plural': 'Excluded ZIP codes',
                'ordering': ['zip'],
            },
        ),
    ]
