# Generated by Django 4.2.20 on 2026-07-08 12:31

from django.db import migrations, models


def backfill_origin(apps, schema_editor):
    """Existing rows default to 'system' (the field default). Flip the ones that
    were clearly created by an agent by hand to 'agent'.

    A manual ticket is opened via the Work Queue with a chosen ``source`` and no
    ``import_run``, and never uses the system-only ``system_change_detected``
    type. Import/daily-sync tickets always carry an ``import_run`` (and stay
    'system'). This is a best-effort backfill for history; every NEW ticket sets
    its origin explicitly (or inherits the 'system' default) from now on."""
    Ticket = apps.get_model('api', 'Ticket')
    (
        Ticket.objects
        .exclude(source='')
        .filter(import_run__isnull=True)
        .exclude(type__code='system_change_detected')
        .update(origin='agent')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_seed_excluded_zip_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='origin',
            field=models.CharField(choices=[('system', 'System'), ('agent', 'Agent')], db_index=True, default='system', max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='origin',
            field=models.CharField(choices=[('system', 'System'), ('agent', 'Agent')], db_index=True, default='system', max_length=10),
        ),
        migrations.RunPython(backfill_origin, migrations.RunPython.noop),
    ]
