# Generated by Django 4.2.20 on 2026-07-08 15:47

from django.db import migrations, models


def _seed_status_changed_at(apps, schema_editor):
    """Seed status_changed_at for existing non-Active profiles so the new
    "Paused/Out of Orbit since" columns aren't blank for current members. Uses
    updated_at as the best available proxy for the historical status flip."""
    MemberDietaryProfile = apps.get_model("api", "MemberDietaryProfile")
    (
        MemberDietaryProfile.objects.filter(
            status__in=["out_of_orbit", "paused"],
            status_changed_at__isnull=True,
        ).update(status_changed_at=models.F("updated_at"))
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_historicalticket_origin_ticket_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdietaryprofile',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(_seed_status_changed_at, migrations.RunPython.noop),
    ]
