# Generated by Django 4.2.20 on 2026-07-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_memberdietaryprofile_status_changed_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollmentverification',
            name='uniq_enrollment_verification_per_case',
        ),
        migrations.AlterField(
            model_name='enrollmentverification',
            name='stage',
            field=models.CharField(choices=[('pending_validation', 'Pending Validation'), ('validated', 'Validated'), ('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('kitchen_assignment', 'Kitchen Assignment'), ('service_active', 'Service Active'), ('service_complete', 'Service Complete'), ('closed', 'Closed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled'), ('disregarded', 'Disregarded')], db_index=True, default='pending_verification', max_length=25),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(choices=[('consent_granted', 'Consent Granted'), ('insurance', 'Insurance'), ('social_care_coverage', 'Social Care Coverage'), ('screening', 'Screening'), ('assessment', 'Assessment'), ('case_opened', 'Case'), ('case_status_changed', 'Case Status Changed'), ('case_auth_changed', 'Case Authorization Changed'), ('pending_validation', 'Pending Validation'), ('validated', 'Validated'), ('verification_requested', 'Verification Requested'), ('verification_completed', 'Verification Completed'), ('waiting_authorization', 'Waiting Authorization'), ('authorized', 'Authorized'), ('denied', 'Denied'), ('kitchen_assigned', 'Kitchen Assigned'), ('service_activated', 'Service Activated'), ('service_on_hold', 'Service On Hold'), ('service_resumed', 'Service Resumed'), ('service_completed', 'Service Completed'), ('service_closed', 'Service Closed'), ('service_cancelled', 'Service Cancelled'), ('enrolled', 'Enrolled'), ('ticket_created', 'New Ticket Created'), ('delivery_address_changed', 'Delivery Address Changed'), ('out_of_orbit', 'Out of Orbit'), ('member_reactivated', 'Member Reactivated'), ('member_paused', 'Member Paused'), ('member_unpaused', 'Member Unpaused'), ('household_member_added', 'Household Member Added'), ('verification', 'Verification'), ('service', 'Service'), ('verification_disregarded', 'Verification Disregarded')], db_index=True, max_length=30),
        ),
        migrations.AddConstraint(
            model_name='enrollmentverification',
            constraint=models.UniqueConstraint(condition=models.Q(('case__isnull', False), models.Q(('stage__in', ['disregarded', 'cancelled']), _negated=True)), fields=('case',), name='uniq_enrollment_verification_per_case'),
        ),
    ]
