# Generated by Django 4.2.20 on 2026-07-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_remove_enrollmentverification_uniq_enrollment_verification_per_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='verification_disregarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='verification_disregarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
