# Generated by Django 4.2.20 on 2026-07-09 19:38

from django.db import migrations, models
import uuid


def seed_cadences(apps, schema_editor):
    """Seed the configurable Cadence table from the legacy DeliveryCadence enum
    so the existing set is available out of the box and matches the codes stored
    on ProductType.delivery_days_cadence / MemberDeliverySchedule."""
    Cadence = apps.get_model("api", "Cadence")
    seed = [
        ("mon_thu", "Mon/Thu", ["mon", "thu"]),
        ("tue_fri", "Tue/Fri", ["tue", "fri"]),
        # Once-a-week carries no fixed day: the agent picks the single weekday.
        ("once_a_week", "Once a Week", []),
    ]
    for code, label, weekdays in seed:
        Cadence.objects.update_or_create(
            code=code, defaults={"label": label, "weekdays": weekdays, "is_active": True},
        )


def unseed_cadences(apps, schema_editor):
    Cadence = apps.get_model("api", "Cadence")
    Cadence.objects.filter(code__in=["mon_thu", "tue_fri", "once_a_week"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_alter_memberdietaryprofile_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadence',
            fields=[
                ('cadence_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.AddField(
            model_name='kitchen',
            name='cadences',
            field=models.ManyToManyField(blank=True, related_name='kitchens', to='api.cadence'),
        ),
        migrations.RunPython(seed_cadences, unseed_cadences),
    ]
