# Generated by Django 4.2.20 on 2026-07-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_cadence'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_new',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='is_new',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
