# Generated by Django 5.2.16 on 2026-07-13 18:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_enrollmentverification_product_type_override_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('red', 'Red'), ('orange', 'Orange')], max_length=16)),
                ('scope', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=120)),
                ('detail', models.TextField(blank=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], db_index=True, default='active', max_length=16)),
                ('first_detected_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='api.client')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warnings', to='api.enrollmentverification')),
            ],
            options={
                'ordering': ['-severity', 'first_detected_at'],
                'indexes': [models.Index(fields=['status', 'severity'], name='api_memberw_status_b2c143_idx'), models.Index(fields=['enrollment', 'status'], name='api_memberw_enrollm_86ce3e_idx'), models.Index(fields=['code'], name='api_memberw_code_78db83_idx')],
                'constraints': [models.UniqueConstraint(fields=('client', 'code'), name='uniq_member_warning_client_code')],
            },
        ),
    ]
