# Generated by Django 5.2.16 on 2026-07-14 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_alter_timelineevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniteUsExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('export_type', models.CharField(max_length=64)),
                ('importer_type', models.CharField(blank=True, max_length=40)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('unite_state', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('ready', 'Ready'), ('importing', 'Importing'), ('imported', 'Imported'), ('failed', 'Failed')], db_index=True, default='requested', max_length=20)),
                ('file_upload_id', models.CharField(blank=True, max_length=64)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('provider_id', models.CharField(blank=True, max_length=64)),
                ('triggered_by', models.CharField(blank=True, max_length=120)),
                ('error_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('import_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uniteus_exports', to='api.importrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='api_uniteus_status_132b0f_idx')],
            },
        ),
    ]
