# Generated by Django 5.2.16 on 2026-07-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0132_uniteusexport'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniteuscredential',
            name='for_automation',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
