# Generated by Django 5.2.16 on 2026-07-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0133_uniteuscredential_for_automation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnote',
            name='source',
            field=models.CharField(choices=[('unite_us', 'Unite Us'), ('agent', 'Agent'), ('system', 'System'), ('ghl', 'GoHighLevel')], default='unite_us', max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='source',
            field=models.CharField(choices=[('unite_us', 'Unite Us'), ('agent', 'Agent'), ('system', 'System'), ('ghl', 'GoHighLevel')], default='unite_us', max_length=20),
        ),
    ]
