# Generated by Django 5.2.16 on 2026-07-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_alter_historicalnote_source_alter_note_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='vip',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='vip',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
