# Generated by Django 5.2.16 on 2026-07-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0142_allowedstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedstate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
