# Generated by Django 5.2.16 on 2026-07-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0144_alter_client_lifecycle_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='service_authorization_status',
            field=models.CharField(blank=True, choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('expired', 'Expired'), ('never_requested', 'Never Requested')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='service_authorization_status',
            field=models.CharField(blank=True, choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('expired', 'Expired'), ('never_requested', 'Never Requested')], max_length=20),
        ),
    ]
