# Generated by Django 5.2.16 on 2026-07-22 20:56

from django.db import migrations, models


def rename_navigation_category(apps, schema_editor):
    """Rename the ProgramPipeline case_category "Navigation" -> "Care Management".

    Matches the legacy spellings case-insensitively ("NAVIGATION", "Navigation",
    "Navigations") so every routed row picks up the new display name. Only the
    ``case_category`` label changes; ``pipeline_id`` (the authoritative GHL
    routing value) and the derived Case ``case_type`` (still "navigation") are
    untouched, so case classification/routing is unaffected.
    """
    ProgramPipeline = apps.get_model('api', 'ProgramPipeline')
    for legacy in ('navigation', 'navigations'):
        ProgramPipeline.objects.filter(
            case_category__iexact=legacy
        ).update(case_category='Care Management')


def revert_care_management_category(apps, schema_editor):
    """Reverse: restore the "NAVIGATION" label used by the seed data."""
    ProgramPipeline = apps.get_model('api', 'ProgramPipeline')
    ProgramPipeline.objects.filter(
        case_category__iexact='care management'
    ).update(case_category='NAVIGATION')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0145_alter_case_service_authorization_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('navigation', 'Care Management'), ('external_service', 'External Service'), ('internal_service', 'Internal Service'), ('eligibility', 'Eligibility')], default='internal_service', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='case_type',
            field=models.CharField(choices=[('navigation', 'Care Management'), ('external_service', 'External Service'), ('internal_service', 'Internal Service'), ('eligibility', 'Eligibility')], default='internal_service', max_length=20),
        ),
        migrations.RunPython(
            rename_navigation_category,
            revert_care_management_category,
        ),
    ]
