# Generated by Django 5.2.16 on 2026-07-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0146_rename_navigation_to_care_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='lifecycle_stage',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('consent', 'Consent'), ('screened', 'Screening'), ('assessment', 'Assessment'), ('navigation', 'Care Management'), ('eligible', 'Eligible'), ('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('kitchen_assignment', 'Kitchen Assignment'), ('active', 'Active'), ('completed', 'Completed'), ('enrolled', 'Enrolled'), ('cancelled', 'Cancelled'), ('not_eligible', 'Not Eligible'), ('ineligible', 'Ineligible'), ('service_inactive', 'Inactive')], db_index=True, default='inactive', max_length=25),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='lifecycle_stage',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('consent', 'Consent'), ('screened', 'Screening'), ('assessment', 'Assessment'), ('navigation', 'Care Management'), ('eligible', 'Eligible'), ('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('kitchen_assignment', 'Kitchen Assignment'), ('active', 'Active'), ('completed', 'Completed'), ('enrolled', 'Enrolled'), ('cancelled', 'Cancelled'), ('not_eligible', 'Not Eligible'), ('ineligible', 'Ineligible'), ('service_inactive', 'Inactive')], db_index=True, default='inactive', max_length=25),
        ),
    ]
