# Generated by Django 5.2.16 on 2026-07-23 20:54

from django.db import migrations, models


def backfill_is_for_household(apps, schema_editor):
    """Set is_for_household=True for programs whose name contains "household"
    (a household pathway), mirroring ActiveProgram.save()."""
    ActiveProgram = apps.get_model('api', 'ActiveProgram')
    ActiveProgram.objects.filter(
        program_name__icontains='household'
    ).update(is_for_household=True)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0147_rename_navigation_stage_label'),
    ]

    operations = [
        # Preserve the existing table + rows (agents can edit mappings from
        # Settings), just rename ProgramPipeline -> ActiveProgram.
        migrations.RenameModel(
            old_name='ProgramPipeline',
            new_name='ActiveProgram',
        ),
        migrations.RenameIndex(
            model_name='activeprogram',
            new_name='api_activep_case_ca_077e51_idx',
            old_name='api_program_case_ca_e515c4_idx',
        ),
        # The GHL routing columns are no longer modeled.
        migrations.RemoveField(
            model_name='activeprogram',
            name='pipeline_name',
        ),
        migrations.RemoveField(
            model_name='activeprogram',
            name='pipeline_id',
        ),
        migrations.AddField(
            model_name='activeprogram',
            name='is_for_household',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activeprogram',
            name='case_type',
            field=models.CharField(choices=[('food', 'Food'), ('transportation', 'Transportation')], default='food', max_length=20),
        ),
        migrations.RunPython(backfill_is_for_household, migrations.RunPython.noop),
    ]
