# Generated by Django 5.2.16 on 2026-07-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0149_cadence_product_quantities'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='service_category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='service_category',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
