# Generated by Django 5.2.16 on 2026-07-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0150_case_service_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='service_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='service_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
