# Generated by Django 5.2.16 on 2026-07-27 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0152_client_governing_internal_case_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdietaryprofile',
            name='pause_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(choices=[('consent_granted', 'Consent Granted'), ('insurance', 'Insurance'), ('social_care_coverage', 'Social Care Coverage'), ('screening', 'Screening'), ('assessment', 'Assessment'), ('case_opened', 'Case'), ('case_status_changed', 'Case Status Changed'), ('case_auth_changed', 'Case Authorization Changed'), ('pending_validation', 'Pending Validation'), ('validated', 'Validated'), ('verification_requested', 'Verification Requested'), ('verification_completed', 'Verification Completed'), ('waiting_authorization', 'Waiting Authorization'), ('authorized', 'Authorized'), ('denied', 'Denied'), ('kitchen_assigned', 'Kitchen Assigned'), ('service_activated', 'Service Activated'), ('service_on_hold', 'Service On Hold'), ('service_resumed', 'Service Resumed'), ('service_completed', 'Service Completed'), ('service_closed', 'Service Closed'), ('service_cancelled', 'Service Cancelled'), ('enrolled', 'Enrolled'), ('ticket_created', 'New Ticket Created'), ('delivery_address_changed', 'Delivery Address Changed'), ('out_of_orbit', 'Out of Orbit'), ('out_of_range', 'Out of Range'), ('member_reactivated', 'Member Reactivated'), ('member_paused', 'Member Paused'), ('member_unpaused', 'Member Unpaused'), ('member_ineligible', 'Member Ineligible'), ('member_eligibility_restored', 'Eligibility Restored'), ('member_service_inactive', 'Service Inactive'), ('member_service_reactivated', 'Service Reactivated'), ('member_coverage_hold', 'Coverage Hold'), ('member_coverage_restored', 'Coverage Restored'), ('member_governing_case_changed', 'Governing Case Changed'), ('member_program_switched', 'Program Switched'), ('member_case_mismatch', 'Case Mismatch'), ('household_member_added', 'Household Member Added'), ('household_member_removed', 'Household Member Removed'), ('product_type_changed', 'Product Type Changed'), ('dietary_changed', 'Dietary Info Updated'), ('verification', 'Verification'), ('service', 'Service'), ('verification_disregarded', 'Verification Disregarded')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='CaseMismatchFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mismatch_type', models.CharField(choices=[('household_to_individual', 'Household → Individual'), ('individual_to_household', 'Individual → Household')], max_length=32)),
                ('previous_case_id', models.CharField(blank=True, max_length=64)),
                ('new_case_id', models.CharField(blank=True, max_length=64)),
                ('previous_household_type', models.CharField(blank=True, max_length=12)),
                ('new_household_type', models.CharField(blank=True, max_length=12)),
                ('detail', models.TextField(blank=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_by', models.CharField(blank=True, max_length=255)),
                ('dismiss_reason', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_mismatch_flags', to='api.client')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_mismatch_flags', to='api.enrollmentverification')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='api_casemis_status_6f79e0_idx'), models.Index(fields=['enrollment', 'status'], name='api_casemis_enrollm_06cea2_idx')],
                'constraints': [models.UniqueConstraint(fields=('client', 'new_case_id'), name='uniq_case_mismatch_client_new_case')],
            },
        ),
    ]
