# Generated by Django 5.2.16 on 2026-07-27 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0151_alter_case_service_category_and_more'),
        ('api', '0153_case_mismatch_flag_and_pause_lock'),
    ]

    operations = [
    ]
