# Generated by Django 5.2.16 on 2026-07-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0154_merge_20260727_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentverification',
            name='household_type_override',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('household', 'Household')], default='', max_length=12),
        ),
    ]
