# Generated by Django 5.2.16 on 2026-07-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0156_backfill_enrollment_household_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ineligible_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='ineligible_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
