# Generated by Django 5.2.16 on 2026-07-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0160_case_denial_reason_and_authorized_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcase',
            name='authorized_units',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='payer_authorization_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='service_authorization_auto_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='service_authorization_decision_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='service_authorization_denial_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='service_authorization_denial_reason_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='service_authorization_in_review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='service_authorization_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='service_authorization_update_request_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='service_authorization_urgent',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
