# Generated by Django 5.2.16 on 2026-07-30 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0161_historicalcase_service_authorization_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentverification',
            name='close_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='enrollmentverification',
            name='close_reason',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='enrollmentverification',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='api.enrollmentverification'),
        ),
    ]
