# Generated by Django 5.2.16 on 2026-07-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0162_enrollment_supersession_close_reason'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollmentverification',
            name='uniq_enrollment_verification_per_case',
        ),
        migrations.AddConstraint(
            model_name='enrollmentverification',
            constraint=models.UniqueConstraint(condition=models.Q(('case__isnull', False), models.Q(('stage__in', ['disregarded', 'cancelled', 'closed']), _negated=True)), fields=('case',), name='uniq_enrollment_verification_per_case'),
        ),
    ]
