# Generated by Django 5.2.16 on 2026-07-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0163_remove_enrollmentverification_uniq_enrollment_verification_per_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdietaryprofile',
            name='eligibility_paused',
            field=models.BooleanField(default=False),
        ),
    ]
