# Generated by Django 5.2.16 on 2026-07-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0164_memberdietaryprofile_eligibility_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdietaryprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
