# Generated by Django 5.2.16 on 2026-08-03 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0165_memberdietaryprofile_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.agent'),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='created_by_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to='api.agent'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_by_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='TicketActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('status_changed', 'Status Changed'), ('resolved', 'Resolved'), ('reopened', 'Reopened'), ('note_added', 'Note Added'), ('severity_changed', 'Severity Changed'), ('vip_changed', 'VIP Changed')], max_length=24)),
                ('actor_label', models.CharField(blank=True, max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_activities', to='api.agent')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.ticket')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'indexes': [models.Index(fields=['ticket', 'created_at'], name='api_ticketa_ticket__109e50_idx')],
            },
        ),
    ]
