# Generated by Django 5.2.16 on 2026-08-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0166_historicalticket_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
