# Generated by Django 5.2.16 on 2026-08-04 01:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0168_seed_kitchen_abbreviations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('export_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_key', models.CharField(db_index=True, max_length=64)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('file_key', models.CharField(blank=True, max_length=512)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_exports', to='api.agent')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_key'], name='api_reporte_report__9ce2ff_idx'), models.Index(fields=['status'], name='api_reporte_status_3ff28a_idx'), models.Index(fields=['requested_by', 'created_at'], name='api_reporte_request_85fea4_idx')],
            },
        ),
    ]
