# Generated by Django 5.2.16 on 2026-08-05 15:39

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0170_search_trigram_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdietaryprofile',
            name='conditions',
            field=models.JSONField(blank=True, default=api.models.default_member_conditions),
        ),
        migrations.AddField(
            model_name='memberdietaryprofile',
            name='months_postpartum',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberdietaryprofile',
            name='weeks_gestation',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
