# Generated by Django 5.2.16 on 2026-08-05 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0171_memberdietaryprofile_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentverification',
            name='nutritionist_approved_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentverification',
            name='nutritionist_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutritionist_approved_enrollments', to='api.agent'),
        ),
        migrations.AddField(
            model_name='enrollmentverification',
            name='nutritionist_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='group',
            field=models.CharField(choices=[('Screeners', 'Screeners'), ('Verifiers', 'Verifiers'), ('Nutritionist', 'Nutritionist'), ('Logistics', 'Logistics'), ('Management', 'Management'), ('CS', 'CS')], default='Screeners', max_length=50),
        ),
    ]
