# Generated by Django 5.2.16 on 2026-08-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0174_grandfather_nutritionist_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentverification',
            name='nutritionist_approval_pdf_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='enrollmentverification',
            name='nutritionist_signature_image',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='memberdietaryprofile',
            name='height',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='memberdietaryprofile',
            name='medications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='memberdietaryprofile',
            name='weight',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
