# Generated by Django 5.2.16 on 2026-08-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0175_enrollmentverification_nutritionist_approval_pdf_key_and_more'),
    ]

    operations = [
        # medications was a TextField (default ""); an empty string is not valid
        # JSON, so normalize every row to a JSON array literal before switching
        # the column type. Any pre-existing free text is discarded (the field is
        # brand new and now a multi-select of canonical labels).
        migrations.RunSQL(
            sql="UPDATE api_memberdietaryprofile SET medications = '[]';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='memberdietaryprofile',
            name='medications',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
