# Generated by Django 5.2.16 on 2026-08-05 23:52

from django.db import migrations, models


def rename_denied_to_paused(apps, schema_editor):
    # Rename the value "nutritionist_denied" -> "nutritionist_paused" on existing
    # member statuses + timeline events.
    apps.get_model("api", "MemberDietaryProfile").objects.filter(
        status="nutritionist_denied"
    ).update(status="nutritionist_paused")
    apps.get_model("api", "TimelineEvent").objects.filter(
        event_type="nutritionist_denied"
    ).update(event_type="nutritionist_paused")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0178_alter_memberdietaryprofile_status_and_more'),
    ]

    operations = [
        migrations.RunPython(rename_denied_to_paused, noop),
        migrations.AlterField(
            model_name='memberdietaryprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('out_of_orbit', 'Out of Orbit'), ('out_of_range', 'Out of Range'), ('paused', 'Paused'), ('inactive', 'Inactive'), ('nutritionist_paused', 'Nutritionist Paused')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(choices=[('consent_granted', 'Consent Granted'), ('insurance', 'Insurance'), ('social_care_coverage', 'Social Care Coverage'), ('screening', 'Screening'), ('assessment', 'Assessment'), ('case_opened', 'Case'), ('case_status_changed', 'Case Status Changed'), ('case_auth_changed', 'Case Authorization Changed'), ('pending_validation', 'Pending Validation'), ('validated', 'Validated'), ('verification_requested', 'Verification Requested'), ('verification_completed', 'Verification Completed'), ('waiting_authorization', 'Waiting Authorization'), ('authorized', 'Authorized'), ('denied', 'Denied'), ('nutritionist_approved', 'Nutritionist Approved'), ('nutritionist_paused', 'Nutritionist Paused'), ('kitchen_assigned', 'Kitchen Assigned'), ('service_activated', 'Service Activated'), ('service_on_hold', 'Service On Hold'), ('service_resumed', 'Service Resumed'), ('service_completed', 'Service Completed'), ('service_closed', 'Service Closed'), ('service_cancelled', 'Service Cancelled'), ('enrolled', 'Enrolled'), ('ticket_created', 'New Ticket Created'), ('delivery_address_changed', 'Delivery Address Changed'), ('out_of_orbit', 'Out of Orbit'), ('out_of_range', 'Out of Range'), ('member_reactivated', 'Member Reactivated'), ('member_paused', 'Member Paused'), ('member_unpaused', 'Member Unpaused'), ('member_ineligible', 'Member Ineligible'), ('member_eligibility_restored', 'Eligibility Restored'), ('member_service_inactive', 'Service Inactive'), ('member_service_reactivated', 'Service Reactivated'), ('member_coverage_hold', 'Coverage Hold'), ('member_coverage_restored', 'Coverage Restored'), ('member_governing_case_changed', 'Governing Case Changed'), ('member_program_switched', 'Program Switched'), ('member_case_mismatch', 'Case Mismatch'), ('household_member_added', 'Household Member Added'), ('household_member_removed', 'Household Member Removed'), ('product_type_changed', 'Product Type Changed'), ('dietary_changed', 'Dietary Info Updated'), ('verification', 'Verification'), ('service', 'Service'), ('verification_disregarded', 'Verification Disregarded')], db_index=True, max_length=30),
        ),
    ]
