# Generated by Django 5.2.16 on 2026-08-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0181_seed_meal_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdietaryprofile',
            name='meal_plan',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
