# Generated by Django 5.2.16 on 2026-08-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0182_memberdietaryprofile_meal_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdietaryprofile',
            name='meal_plan_other',
            field=models.TextField(blank=True),
        ),
    ]
