# Generated by Django 5.2.16 on 2026-08-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0183_memberdietaryprofile_meal_plan_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdietaryprofile',
            name='medical_diet_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='memberdietaryprofile',
            name='on_medical_diet',
            field=models.BooleanField(default=False),
        ),
    ]
