# Generated by Django 5.2.16 on 2026-08-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0184_memberdietaryprofile_medical_diet_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdietaryprofile',
            name='assessment_notes',
            field=models.TextField(blank=True),
        ),
    ]
