# Generated by Django 5.2.16 on 2026-08-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0185_memberdietaryprofile_assessment_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdietaryprofile',
            name='nutritionist_pdf_key',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
