# Generated by Django 5.2.16 on 2026-08-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0188_refresh_ticket_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='subtitle',
            field=models.TextField(blank=True),
        ),
    ]
