# Generated by Django 5.2.16 on 2026-08-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0190_clienttag_client_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdietaryprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('out_of_orbit', 'Out of Orbit'), ('out_of_range', 'Out of Range'), ('paused', 'Paused'), ('inactive', 'Inactive'), ('nutritionist_paused', 'Nutritionist Paused')], db_index=True, default='pending', max_length=20),
        ),
    ]
