# Generated by Django 5.2.16 on 2026-08-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0192_alter_timelineevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='signature_image',
            field=models.TextField(blank=True),
        ),
    ]
