# Generated by Django 5.2.16 on 2026-08-12 19:19

from django.db import migrations, models


def seed_to_extend(apps, schema_editor):
    """Default True for internal-service reauthorization programs: category is
    "Internal Services" and the program name starts with "Reauthorization: "."""
    ActiveProgram = apps.get_model("api", "ActiveProgram")
    ActiveProgram.objects.filter(
        case_category="Internal Services",
        program_name__startswith="Reauthorization: ",
    ).update(to_extend=True)


def unseed_to_extend(apps, schema_editor):
    ActiveProgram = apps.get_model("api", "ActiveProgram")
    ActiveProgram.objects.filter(
        case_category="Internal Services",
        program_name__startswith="Reauthorization: ",
    ).update(to_extend=False)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0193_agent_signature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeprogram',
            name='to_extend',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(seed_to_extend, unseed_to_extend),
    ]
