# Generated by Django 5.2.16 on 2026-08-12 20:47

from django.db import migrations, models


def backfill_is_extension(apps, schema_editor):
    """Flag existing cases whose program_name matches a to_extend ActiveProgram.

    Uses ``.update()`` (no history signals) so historical rows aren't churned.
    """
    ActiveProgram = apps.get_model("api", "ActiveProgram")
    Case = apps.get_model("api", "Case")
    names = list(
        ActiveProgram.objects.filter(to_extend=True).values_list(
            "program_name", flat=True
        )
    )
    if not names:
        return
    # Case-insensitive match on each to_extend program name.
    from django.db.models import Q
    q = Q()
    for n in names:
        q |= Q(program_name__iexact=n)
    Case.objects.filter(q).update(is_extension=True)


def unset_is_extension(apps, schema_editor):
    Case = apps.get_model("api", "Case")
    Case.objects.filter(is_extension=True).update(is_extension=False)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0194_activeprogram_to_extend'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_extension',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='is_extension',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_is_extension, unset_is_extension),
    ]
