# Generated by Django 5.2.16 on 2026-08-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0195_case_is_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentverification',
            name='stage',
            field=models.CharField(choices=[('pending_validation', 'Pending Validation'), ('validated', 'Validated'), ('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('kitchen_assignment', 'Kitchen Assignment'), ('service_active', 'Service Active'), ('service_complete', 'Service Complete'), ('closed', 'Closed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled'), ('disregarded', 'Disregarded'), ('scheduled_extension', 'Reauthorization - Waiting')], db_index=True, default='pending_verification', max_length=25),
        ),
    ]
