# Generated by Django 5.2.16 on 2026-08-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0196_enrollment_scheduled_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdeliveryschedule',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('waiting', 'Waiting')], db_index=True, default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceschedule',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('waiting', 'Waiting')], default='scheduled', max_length=20),
        ),
    ]
