# Generated by Django 5.2.16 on 2026-08-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0197_schedulestatus_waiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeprogram',
            name='to_extend',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='case',
            name='is_extension',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='is_extension',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
