# Generated by Django 5.2.16 on 2026-08-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0199_member_status_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='migrated_from_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='migrated_from_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
