# Generated by Django 5.2.16 on 2026-08-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0201_alter_timelineevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='migrated_from_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='migrated_from_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, null=True),
        ),
    ]
