# Generated by Django 5.2.16 on 2026-08-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0202_alter_client_migrated_from_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.CharField(db_index=True, max_length=5, unique=True)),
                ('borough', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service ZIP code',
                'verbose_name_plural': 'Service ZIP codes',
                'ordering': ['zip'],
            },
        ),
    ]
