# Generated by Django 5.2.16 on 2026-08-19 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0204_seed_service_zip_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentverification',
            name='previous_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by_enrollments', to='api.case'),
        ),
    ]
