# Generated by Django 5.2.16 on 2026-08-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0205_enrollmentverification_previous_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentverification',
            name='hidden_misinformation',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
