# Generated by Django 5.2.16 on 2026-08-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0207_case_client_type_dateopened_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='internal_case_opened_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='internal_case_opened_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
