# Generated by Django 5.2.16 on 2026-08-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0208_client_internal_case_opened_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='created_by_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='screening',
            name='facilitator_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
