# Generated by Django 5.2.16 on 2026-08-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0209_assessment_created_by_id_assessment_created_by_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='facilitator_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
