# Generated by Django 5.2.16 on 2026-08-24 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0210_assessment_facilitator_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorder',
            name='proof_of_delivery',
        ),
        migrations.CreateModel(
            name='DeliveryOrderProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_key', models.CharField(max_length=500)),
                ('file_url', models.URLField(blank=True, max_length=1000)),
                ('source_url', models.TextField(blank=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('driver', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('source_report', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_order_proofs', to='api.deliverycompany')),
                ('delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='api.deliveryorder')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['delivery_order'], name='api_deliver_deliver_040cd1_idx')],
                'constraints': [models.UniqueConstraint(fields=('delivery_order', 'content_hash'), name='unique_delivery_order_proof_hash')],
            },
        ),
    ]
