# Generated by Django 5.2.16 on 2026-08-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0211_remove_deliveryorder_proof_of_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorderproof',
            name='route_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
