# Generated by Django 5.2.16 on 2026-08-24 20:54
#
# Phase 0 analytics tuning: add indexes the live Members/Data list + dashboards
# filter/sort on. Created CONCURRENTLY (atomic=False) so building them on the
# large prod tables (api_case, api_enrollmentverification, ...) does NOT take a
# write lock -- the app keeps serving while each index builds.

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    # CREATE INDEX CONCURRENTLY cannot run inside a transaction.
    atomic = False

    dependencies = [
        ('api', '0212_deliveryorderproof_route_id'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='case',
            index=models.Index(fields=['case_type', 'date_opened'], name='api_case_type_dopen_idx'),
        ),
        AddIndexConcurrently(
            model_name='case',
            index=models.Index(fields=['case_type', 'case_closed_at'], name='api_case_type_closed_idx'),
        ),
        AddIndexConcurrently(
            model_name='deliveryorder',
            index=models.Index(fields=['member', 'delivered_at'], name='api_deliver_member__0fb62a_idx'),
        ),
        AddIndexConcurrently(
            model_name='enrollmentverification',
            index=models.Index(fields=['kitchen'], name='api_enrollm_kitchen_ea1b05_idx'),
        ),
        AddIndexConcurrently(
            model_name='enrollmentverification',
            index=models.Index(fields=['opened_at'], name='api_enrollm_opened__d9f37e_idx'),
        ),
        AddIndexConcurrently(
            model_name='insurance',
            index=models.Index(fields=['expired_at'], name='api_insuran_expired_5c50c4_idx'),
        ),
        AddIndexConcurrently(
            model_name='socialcarecoverage',
            index=models.Index(fields=['expired_at'], name='api_socialc_expired_4fc8f8_idx'),
        ),
    ]
