# Generated by Django 5.2.16 on 2026-08-24 20:59
#
# Phase 0: index the Members/Data "Lead source" filter. Concurrent build so it
# takes no write lock on the large api_client table.

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('api', '0213_case_api_case_type_dopen_idx_and_more'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='client',
            index=models.Index(fields=['lead_source'], name='api_client_lead_so_b92b73_idx'),
        ),
    ]
