# Generated by Django 5.2.16 on 2026-08-24 21:16

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0214_client_api_client_lead_so_b92b73_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentAnalytics',
            fields=[
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='analytics', serialize=False, to='api.enrollmentverification')),
                ('client_id', models.UUIDField(db_index=True)),
                ('household_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('case_id', models.UUIDField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('stage', models.CharField(blank=True, db_index=True, max_length=25)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('medicaid_id', models.CharField(blank=True, max_length=64)),
                ('dob', models.DateField(blank=True, db_index=True, null=True)),
                ('member_created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('care_coordinator', models.CharField(blank=True, db_index=True, max_length=255)),
                ('primary_care_coordinator', models.CharField(blank=True, max_length=255)),
                ('cadence', models.CharField(blank=True, db_index=True, max_length=40)),
                ('kitchen_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('kitchen_name', models.CharField(blank=True, max_length=255)),
                ('menu_type', models.CharField(blank=True, db_index=True, max_length=120)),
                ('current_delivery_status', models.CharField(blank=True, db_index=True, max_length=30)),
                ('last_po_delivery_status', models.CharField(blank=True, max_length=30)),
                ('last_delivered_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('insurance_status', models.CharField(blank=True, db_index=True, max_length=20)),
                ('insurance_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('social_status', models.CharField(blank=True, db_index=True, max_length=20)),
                ('social_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attestation_status', models.CharField(blank=True, db_index=True, max_length=20)),
                ('attestation_requested_at', models.DateTimeField(blank=True, null=True)),
                ('attestation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('has_screening', models.BooleanField(db_index=True, default=False)),
                ('screening_at', models.DateTimeField(blank=True, null=True)),
                ('has_eligibility_assessment', models.BooleanField(db_index=True, default=False)),
                ('eligibility_assessment_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('verified_by_name', models.CharField(blank=True, max_length=255)),
                ('case_type', models.CharField(blank=True, db_index=True, max_length=20)),
                ('case_status', models.CharField(blank=True, db_index=True, max_length=25)),
                ('auth_status', models.CharField(blank=True, db_index=True, max_length=20)),
                ('case_opened_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('program_name', models.CharField(blank=True, max_length=255)),
                ('allergies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('medical_conditions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None)),
                ('medications', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None)),
                ('eligible_services', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('refreshed_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['allergies'], name='ea_allergies_gin'), django.contrib.postgres.indexes.GinIndex(fields=['medical_conditions'], name='ea_conditions_gin'), django.contrib.postgres.indexes.GinIndex(fields=['medications'], name='ea_medications_gin'), django.contrib.postgres.indexes.GinIndex(fields=['eligible_services'], name='ea_elig_services_gin')],
            },
        ),
    ]
