# Generated by Django 5.2.16 on 2026-08-25 14:50
#
# Index EnrollmentVerification.verified_by for the "Verified by" filter on the
# Members + Verification lists. Concurrent build so it takes no write lock.

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('api', '0215_enrollmentanalytics'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='enrollmentverification',
            index=models.Index(fields=['verified_by'], name='api_enrollm_verifie_ebda09_idx'),
        ),
    ]
