# Generated by Django 5.2.16 on 2026-08-25 14:56
#
# Drop the redundant explicit indexes on kitchen_id / verified_by_id: both are
# ForeignKeys, so Django's automatic FK index already covers them (confirmed via
# EXPLAIN -- the "Verified by" filter uses the auto FK index). Dropped
# CONCURRENTLY so it takes no lock on the large table.

from django.contrib.postgres.operations import RemoveIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('api', '0216_enrollmentverification_api_enrollm_verifie_ebda09_idx'),
    ]

    operations = [
        RemoveIndexConcurrently(
            model_name='enrollmentverification',
            name='api_enrollm_kitchen_ea1b05_idx',
        ),
        RemoveIndexConcurrently(
            model_name='enrollmentverification',
            name='api_enrollm_verifie_ebda09_idx',
        ),
    ]
