# Generated by Django 5.2.16 on 2026-08-25 15:21

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0217_remove_enrollmentverification_api_enrollm_kitchen_ea1b05_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='case_closed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='eligibility',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='lead_source',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='out_of_orbit',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='out_of_range',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='pause_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='paused',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='program_status',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='program_type',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='requested_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='service_type',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='team',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='ticket_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='verification_state',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='verified_by_id_str',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='enrollmentanalytics',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='ea_tags_gin'),
        ),
        migrations.AddIndex(
            model_name='enrollmentanalytics',
            index=django.contrib.postgres.indexes.GinIndex(fields=['ticket_types'], name='ea_ticket_types_gin'),
        ),
    ]
