# Generated by Django 5.2.16 on 2026-08-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0218_enrollmentanalytics_case_closed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentanalytics',
            name='program_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
