# Generated by Django 5.2.16 on 2026-08-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0219_alter_enrollmentanalytics_program_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='company_status',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
