# Generated by Django 5.2.16 on 2026-08-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0220_enrollmentanalytics_company_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='delivery_company',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='nutritionist',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
