# Generated by Django 5.2.16 on 2026-08-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0221_enrollmentanalytics_delivery_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentanalytics',
            name='nutritionist',
        ),
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='nutritionist_status',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
