# Generated by Django 5.2.16 on 2026-08-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0222_remove_enrollmentanalytics_nutritionist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='has_been_delivered',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
