# Generated by Django 5.2.16 on 2026-08-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0223_enrollmentanalytics_has_been_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentanalytics',
            name='has_been_delivered',
        ),
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='in_any_po',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
