# Generated by Django 5.2.16 on 2026-08-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0225_enrollmentanalytics_member_grain'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='has_pending_verification_enrollment',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='has_verified_enrollment',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
