# Generated by Django 5.2.16 on 2026-08-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0226_enrollmentanalytics_has_pending_verification_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='governing_internal_case_opened_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='governing_internal_case_opened_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
