# Generated by Django 5.2.16 on 2026-08-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0227_client_governing_internal_case_opened_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='governing_verification_completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='governing_verification_requested_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='governing_verification_completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='governing_verification_requested_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
