# Generated by Django 5.2.16 on 2026-08-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0228_client_governing_verification_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='governing_internal_case_authorized_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='governing_internal_case_closed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='governing_internal_case_status',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='governing_internal_case_authorized_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='governing_internal_case_closed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='governing_internal_case_status',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
