# Generated by Django 5.2.16 on 2026-08-26 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0229_client_governing_internal_case_authorized_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='governing_kitchen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.kitchen'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='governing_kitchen',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.kitchen'),
        ),
    ]
