# Generated by Django 5.2.16 on 2026-08-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0230_client_governing_kitchen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='governing_program_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='governing_program_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
    ]
