# Generated by Django 5.2.16 on 2026-08-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0231_client_governing_program_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='governing_internal_case_status',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='governing_program_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='governing_internal_case_status',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='governing_program_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16, null=True),
        ),
    ]
