# Generated by Django 5.2.16 on 2026-08-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0232_alter_client_governing_internal_case_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='has_never_requested_verification',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
