# Generated by Django 5.2.16 on 2026-08-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0234_alter_timelineevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='added_to_system_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='added_to_system_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
