# Generated by Django 5.2.16 on 2026-08-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0235_case_added_to_system_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='internal_case_added_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='internal_case_added_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['case_type', 'added_to_system_at'], name='api_case_type_added_idx'),
        ),
    ]
