# Generated by Django 5.2.16 on 2026-08-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0236_client_internal_case_added_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='screening_agent',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
