# Generated by Django 5.2.16 on 2026-08-31 17:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0237_enrollmentanalytics_screening_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='phone_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None),
        ),
    ]
