# Generated by Django 5.2.16 on 2026-08-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0238_enrollmentanalytics_phone_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsRebuildRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rows', models.IntegerField(default=0)),
                ('pruned', models.IntegerField(default=0)),
                ('trigger', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
