# Generated by Django 5.2.16 on 2026-09-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0239_analyticsrebuildrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='urgent_care_dismissed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='urgent_care_dismissed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
