# Generated by Django 5.2.16 on 2026-09-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0241_seed_cadence_switch_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='auth_end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='auth_start_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='last_po_delivery_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='pause_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
