# Generated by Django 5.2.16 on 2026-09-03 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0242_enrollmentanalytics_auth_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_notes', to='api.agent')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.purchaseorder')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['purchase_order', 'created_at'], name='api_purchas_purchas_99e92b_idx')],
            },
        ),
    ]
