# Generated by Django 5.2.16 on 2026-09-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0243_purchaseordernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='hyros_enrolled_pushed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='hyros_enrolled_pushed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
