# Generated by Django 5.2.16 on 2026-09-03 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0245_update_service_zip_whitelist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcludedZipCode',
        ),
    ]
