# Generated by Django 5.2.16 on 2026-09-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0246_delete_excludedzipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeprogram',
            name='service_type',
            field=models.CharField(blank=True, choices=[('clinically_appropriate_meals', 'Clinically Appropriate Meals'), ('medically_tailored_meals', 'Medically Tailored Meals (MTM)'), ('food_prescriptions', 'Food Prescriptions (Voucher / Boxes)')], db_default='', default='', max_length=40),
        ),
    ]
