"""Seed ``ActiveProgram.service_type`` from the program name.

``program_name`` encodes service + population + borough + an optional
"Reauthorization: " prefix, so the service is derived from the name PREFIX after
stripping that prefix:

    Clinically Appropriate Meals ...                       -> clinically_appropriate_meals
    Medically Tailored Meals (MTM) ...                     -> medically_tailored_meals
    Medically Tailored or Nutritionally Appropriate
        Food Prescriptions: {Boxes,Voucher} ...            -> food_prescriptions

Programs that aren't one of these services (external services, screening,
eligibility, care management, pantry stocking, nutritional counseling) are left
blank -- an agent sets those from Settings > Programs if needed.

Only fills BLANK rows, so re-running never overwrites an agent's manual choice.
"""
import re

from django.db import migrations

# (name prefix -> service_type code). Order matters only in that the prefixes
# are mutually exclusive; kept explicit for readability.
RULES = [
    ("Clinically Appropriate Meals", "clinically_appropriate_meals"),
    ("Medically Tailored Meals (MTM)", "medically_tailored_meals"),
    (
        "Medically Tailored or Nutritionally Appropriate Food Prescriptions:",
        "food_prescriptions",
    ),
]

_REAUTH = re.compile(r"^\s*reauthorization:\s*", re.I)


def service_type_for(program_name):
    # Case-insensitive prefix match: the names are machine-generated by Unite Us
    # and consistent, but a manually-added row shouldn't silently miss out.
    base = _REAUTH.sub("", program_name or "").strip().casefold()
    for prefix, code in RULES:
        if base.startswith(prefix.casefold()):
            return code
    return ""


def seed(apps, schema_editor):
    ActiveProgram = apps.get_model("api", "ActiveProgram")
    updates = []
    for p in ActiveProgram.objects.all().only("id", "program_name", "service_type"):
        if (p.service_type or "").strip():
            continue  # never clobber a value already set
        code = service_type_for(p.program_name)
        if code:
            p.service_type = code
            updates.append(p)
    if updates:
        ActiveProgram.objects.bulk_update(updates, ["service_type"], batch_size=500)


def unseed(apps, schema_editor):
    """Reverse: clear only the values this migration could have set."""
    ActiveProgram = apps.get_model("api", "ActiveProgram")
    ActiveProgram.objects.filter(
        service_type__in=[code for _, code in RULES]
    ).update(service_type="")


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0247_activeprogram_service_type"),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
