# Generated by Django 5.2.16 on 2026-09-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0248_seed_activeprogram_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeprogram',
            name='service_type',
            field=models.CharField(blank=True, choices=[('clinically_appropriate_meals', 'Clinically Appropriate Meals'), ('medically_tailored_meals', 'Medically Tailored Meals (MTM)'), ('food_prescriptions', 'Food Prescriptions (Voucher / Boxes)'), ('social_service_case_management', 'Social Service Case Management')], db_default='', default='', max_length=40),
        ),
    ]
