# Generated by Django 5.2.16 on 2026-09-09 17:42

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0252_seed_hybrid_switch_ticket_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCompanyApiClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('secret_hash', models.CharField(max_length=128)),
                ('previous_secret_hash', models.CharField(blank=True, max_length=128)),
                ('previous_secret_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(blank=True, default=api.models.default_partner_scopes)),
                ('allowed_ips', models.JSONField(blank=True, default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_ip', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delivery_api_clients', to='api.agent')),
                ('delivery_company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_client', to='api.deliverycompany')),
            ],
            options={
                'ordering': ['delivery_company__name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_ip', models.CharField(blank=True, max_length=64)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='api.deliverycompanyapiclient')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'expires_at'], name='api_partner_client__265774_idx')],
            },
        ),
    ]
