# Generated by Django 5.2.16 on 2026-09-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0253_deliverycompanyapiclient_partneraccesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_added_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='source',
            field=models.CharField(blank=True, choices=[('extension', 'Extension'), ('import', 'Import')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='client_added_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='source',
            field=models.CharField(blank=True, choices=[('extension', 'Extension'), ('import', 'Import')], db_index=True, max_length=20),
        ),
    ]
