# Generated by Django 5.2.16 on 2026-09-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0255_backfill_client_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='member_added_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentanalytics',
            name='source',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
