# Generated by Django 5.2.16 on 2026-09-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0256_enrollmentanalytics_member_added_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='source',
            field=models.CharField(blank=True, choices=[('extension', 'Extension'), ('import', 'Import')], db_default='', db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollmentanalytics',
            name='source',
            field=models.CharField(blank=True, db_default='', db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='source',
            field=models.CharField(blank=True, choices=[('extension', 'Extension'), ('import', 'Import')], db_default='', db_index=True, max_length=20),
        ),
    ]
