# Generated by Django 5.2.16 on 2026-09-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0259_member_service_carry_blocked_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdietaryprofile',
            name='pause_prior_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('active', 'Active'), ('out_of_orbit', 'Out of Orbit'), ('out_of_range', 'Out of Range'), ('paused', 'Paused'), ('inactive', 'Inactive'), ('nutritionist_paused', 'Nutritionist Paused'), ('removed', 'Removed')], max_length=32),
        ),
    ]
