# Generated by Django 5.2.16 on 2026-09-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0260_member_pause_prior_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeprogram',
            name='case_type',
            field=models.CharField(choices=[('food', 'Food'), ('housing', 'Housing'), ('transportation', 'Transportation')], default='food', max_length=20),
        ),
    ]
