# Generated by Django 5.2.16 on 2026-09-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0262_seed_housing_internal_service_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeprogram',
            name='service_type',
            field=models.CharField(blank=True, choices=[('clinically_appropriate_meals', 'Clinically Appropriate Meals'), ('medically_tailored_meals', 'Medically Tailored Meals (MTM)'), ('food_prescriptions', 'Food Prescriptions (Voucher / Boxes)'), ('social_service_case_management', 'Social Service Case Management'), ('environmental_exposure_assessment', 'Environmental Exposure Assessment')], db_default='', default='', max_length=40),
        ),
    ]
