# Generated by Django 5.2.16 on 2026-09-17 00:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0266_seed_home_remediation_programs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_key', models.CharField(max_length=500)),
                ('file_url', models.URLField(blank=True, max_length=1000)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['received_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_role', models.CharField(choices=[('vendor', 'Vendor'), ('member', 'Member')], max_length=10)),
                ('signer_name', models.CharField(blank=True, max_length=255)),
                ('s3_key', models.CharField(blank=True, max_length=500)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['signed_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchSubmission',
            fields=[
                ('dispatch_submission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(choices=[('active', 'Active'), ('voided', 'Voided')], db_index=True, default='active', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('pdf_s3_key', models.CharField(blank=True, max_length=500)),
                ('pdf_sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sequence'],
            },
        ),
        migrations.CreateModel(
            name='DispatchUniteUsUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('uniteus_ref', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('calendar_event_ref', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VendorUser',
            fields=[
                ('vendor_user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['vendor__name', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='stageevent',
            name='entity_type',
            field=models.CharField(choices=[('client', 'Client'), ('enrollment', 'Enrollment'), ('dispatch_order', 'Dispatch Order')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(choices=[('consent_granted', 'Consent Granted'), ('consent_withdrawn', 'Consent Withdrawn'), ('insurance', 'Insurance'), ('social_care_coverage', 'Social Care Coverage'), ('screening', 'Screening'), ('assessment', 'Assessment'), ('case_opened', 'Case'), ('case_status_changed', 'Case Status Changed'), ('case_auth_changed', 'Case Authorization Changed'), ('pending_validation', 'Pending Validation'), ('validated', 'Validated'), ('verification_requested', 'Verification Requested'), ('verification_completed', 'Verification Completed'), ('waiting_authorization', 'Waiting Authorization'), ('authorized', 'Authorized'), ('denied', 'Denied'), ('nutritionist_approved', 'Nutritionist Approved'), ('nutritionist_paused', 'Nutritionist Paused'), ('awaiting_kitchen', 'Awaiting Kitchen Assignment'), ('kitchen_assigned', 'Kitchen Assigned'), ('service_activated', 'Service Activated'), ('service_on_hold', 'Service On Hold'), ('service_resumed', 'Service Resumed'), ('service_completed', 'Service Completed'), ('service_closed', 'Service Closed'), ('service_cancelled', 'Service Cancelled'), ('enrolled', 'Enrolled'), ('dispatch_created', 'Assessment Order Created'), ('dispatch_scheduled', 'Dispatch Scheduled'), ('dispatch_confirmed', 'Dispatch Confirmed'), ('dispatch_visit_started', 'Vendor Visit Started'), ('dispatch_pending_submission', 'Dispatch Pending Submission'), ('dispatch_submitted', 'Dispatch Submitted'), ('dispatch_voided', 'Dispatch Submission Voided'), ('dispatch_uploaded', 'Dispatch Uploaded to Unite Us'), ('dispatch_cancelled', 'Dispatch Cancelled'), ('ticket_created', 'New Ticket Created'), ('delivery_address_changed', 'Delivery Address Changed'), ('out_of_orbit', 'Out of Orbit'), ('out_of_range', 'Out of Range'), ('client_migrated', 'Client Migrated'), ('member_reactivated', 'Member Reactivated'), ('member_paused', 'Member Paused'), ('member_unpaused', 'Member Unpaused'), ('member_ineligible', 'Member Ineligible'), ('member_eligibility_restored', 'Eligibility Restored'), ('member_service_inactive', 'Service Inactive'), ('member_service_reactivated', 'Service Reactivated'), ('member_coverage_hold', 'Coverage Hold'), ('member_coverage_restored', 'Coverage Restored'), ('member_governing_case_changed', 'Governing Case Changed'), ('member_program_switched', 'Program Switched'), ('member_case_mismatch', 'Case Mismatch'), ('member_service_carry_blocked', 'Not Returned To Service'), ('household_member_added', 'Household Member Added'), ('household_member_removed', 'Household Member Removed'), ('product_type_changed', 'Product Type Changed'), ('dietary_changed', 'Dietary Info Updated'), ('verification', 'Verification'), ('service', 'Service'), ('verification_disregarded', 'Verification Disregarded')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='DispatchOrder',
            fields=[
                ('dispatch_order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('assessment', 'Dwelling Assessment'), ('remediation', 'Home Remediation')], db_index=True, max_length=20)),
                ('dwellings', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending_schedule', 'Pending Schedule'), ('confirmed', 'Confirmed'), ('pending_submission', 'Pending Submission'), ('submitted', 'Submitted'), ('uploaded', 'Uploaded'), ('cancelled', 'Cancelled')], db_index=True, default='pending_schedule', max_length=20)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('contact_phone_type', models.CharField(blank=True, max_length=10)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('address_city', models.CharField(blank=True, max_length=120)),
                ('address_state', models.CharField(blank=True, max_length=40)),
                ('address_zip', models.CharField(blank=True, max_length=20)),
                ('address_formatted', models.CharField(blank=True, max_length=500)),
                ('address_place_id', models.CharField(blank=True, max_length=255)),
                ('address_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address_notes', models.TextField(blank=True)),
                ('referral_type', models.CharField(blank=True, choices=[('mobility', 'Mobility'), ('ventilation', 'Ventilation'), ('combined', 'Combined')], max_length=20)),
                ('consent_to_call', models.BooleanField(default=False)),
                ('consent_to_text', models.BooleanField(default=False)),
                ('consent_method', models.CharField(blank=True, default='verbal', max_length=20)),
                ('consent_captured_at', models.DateTimeField(blank=True, null=True)),
                ('ecm_billed_confirmed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_orders', to='api.case')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_orders', to='api.client')),
                ('consent_captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_consents_captured', to='api.agent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_orders_created', to='api.agent')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.dispatchorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatch_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='api.dispatchorder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_key', models.CharField(max_length=500)),
                ('file_url', models.URLField(blank=True, max_length=1000)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('doc_type', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_documents', to='api.agent')),
                ('dispatch_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.dispatchorder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchAvailabilityWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatch_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_windows', to='api.dispatchorder')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='stageevent',
            name='dispatch_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_events', to='api.dispatchorder'),
        ),
        migrations.AddIndex(
            model_name='stageevent',
            index=models.Index(fields=['dispatch_order', 'entered_at'], name='api_stageev_dispatc_38909e_idx'),
        ),
        migrations.AddField(
            model_name='dispatchproof',
            name='dispatch_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='api.dispatchorder'),
        ),
        migrations.AddField(
            model_name='dispatchproof',
            name='finding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='api.dispatchfinding'),
        ),
        migrations.AddField(
            model_name='dispatchsubmission',
            name='dispatch_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.dispatchorder'),
        ),
        migrations.AddField(
            model_name='dispatchsignature',
            name='dispatch_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='api.dispatchsubmission'),
        ),
        migrations.AddField(
            model_name='dispatchuniteusupload',
            name='dispatch_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uniteus_uploads', to='api.dispatchorder'),
        ),
        migrations.AddField(
            model_name='dispatchuniteusupload',
            name='dispatch_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uniteus_uploads', to='api.dispatchsubmission'),
        ),
        migrations.AddField(
            model_name='dispatchuniteusupload',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_uniteus_uploads', to='api.agent'),
        ),
        migrations.AddField(
            model_name='dispatchvisit',
            name='dispatch_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='api.dispatchorder'),
        ),
        migrations.AddField(
            model_name='dispatchorder',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_orders', to='api.vendor'),
        ),
        migrations.AddField(
            model_name='vendoruser',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.vendor'),
        ),
        migrations.AddField(
            model_name='dispatchsubmission',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_submissions', to='api.vendoruser'),
        ),
        migrations.AddField(
            model_name='dispatchsubmission',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_submissions_voided', to='api.vendoruser'),
        ),
        migrations.AddField(
            model_name='dispatchdocument',
            name='uploaded_by_vendor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_documents', to='api.vendoruser'),
        ),
        migrations.AddConstraint(
            model_name='dispatchproof',
            constraint=models.UniqueConstraint(fields=('dispatch_order', 'content_hash'), name='one_proof_per_hash_per_order'),
        ),
        migrations.AddConstraint(
            model_name='dispatchsignature',
            constraint=models.UniqueConstraint(fields=('dispatch_submission', 'signer_role'), name='one_signature_per_role_per_submission'),
        ),
        migrations.AddIndex(
            model_name='dispatchorder',
            index=models.Index(fields=['client', 'kind'], name='api_dispatc_client__eef6b2_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchorder',
            index=models.Index(fields=['vendor', 'status'], name='api_dispatc_vendor__31340c_idx'),
        ),
        migrations.AddConstraint(
            model_name='dispatchorder',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'assessment')), fields=('client',), name='one_assessment_order_per_client'),
        ),
        migrations.AddConstraint(
            model_name='dispatchorder',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'remediation')), fields=('case',), name='one_remediation_order_per_case'),
        ),
        migrations.AddConstraint(
            model_name='vendoruser',
            constraint=models.UniqueConstraint(condition=models.Q(('is_admin', True)), fields=('vendor',), name='one_admin_user_per_vendor'),
        ),
        migrations.AddConstraint(
            model_name='dispatchsubmission',
            constraint=models.UniqueConstraint(fields=('dispatch_order', 'sequence'), name='one_submission_per_sequence'),
        ),
        migrations.AddConstraint(
            model_name='dispatchsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('dispatch_order',), name='one_active_submission_per_order'),
        ),
    ]
