# Generated by Django 5.2.16 on 2026-09-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0270_seed_home_accessibility_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='website',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
