# Generated by Django 5.2.16 on 2026-09-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0271_vendor_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchorder',
            name='item',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dispatchorder',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
