# Generated by Django 5.2.16 on 2026-09-17 16:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0272_dispatch_item_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchItem',
            fields=[
                ('dispatch_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('program_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['location', 'item'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='dispatchorder',
            name='one_remediation_order_per_case',
        ),
        migrations.RemoveField(
            model_name='dispatchorder',
            name='item',
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.dispatchorder'),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_items', to='api.case'),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='dispatch_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='api.dispatchorder'),
        ),
        migrations.AddIndex(
            model_name='dispatchitem',
            index=models.Index(fields=['assessment', 'dispatch_order'], name='api_dispatc_assessm_ada5e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='dispatchitem',
            constraint=models.UniqueConstraint(fields=('case',), name='one_item_per_case'),
        ),
    ]
