# Generated by Django 5.2.16 on 2026-09-17 18:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0274_convert_remediation_orders_to_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchQuestionnaire',
            fields=[
                ('dispatch_questionnaire_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modules', models.JSONField(blank=True, default=list)),
                ('template_version', models.PositiveIntegerField(default=1)),
                ('schema_snapshot', models.JSONField(blank=True, default=dict)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('section_other', models.JSONField(blank=True, default=dict)),
                ('interventions', models.JSONField(blank=True, default=list)),
                ('justification', models.TextField(blank=True)),
                ('assessor_notes', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], db_index=True, default='draft', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatch_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='api.dispatchorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
