# Generated by Django 5.2.16 on 2026-09-17 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0275_dispatch_questionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_ip', models.CharField(blank=True, max_length=64)),
                ('device_label', models.CharField(blank=True, max_length=120)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='api.vendoruser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor_user', 'expires_at'], name='api_vendora_vendor__f42b3b_idx')],
            },
        ),
    ]
