# Generated by Django 5.2.16 on 2026-09-17 20:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0276_vendor_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchReminder',
            fields=[
                ('reminder_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('day_before', 'Day before'), ('thirty_min', '30 minutes before')], max_length=16)),
                ('audience', models.CharField(choices=[('vendor', 'Vendor'), ('member', 'Member')], default='vendor', max_length=10)),
                ('send_at', models.DateTimeField(db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='api.dispatchvisit')),
            ],
            options={
                'ordering': ['send_at'],
                'indexes': [models.Index(fields=['send_at', 'sent_at'], name='api_dispatc_send_at_bf2755_idx')],
            },
        ),
        migrations.CreateModel(
            name='MemberMessage',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], max_length=10)),
                ('kind', models.CharField(choices=[('appointment_scheduled', 'Appointment scheduled'), ('appointment_reminder', 'Appointment reminder'), ('appointment_changed', 'Appointment changed'), ('freeform', 'Free text'), ('inbound_reply', 'Inbound reply')], default='freeform', max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('blocked', 'Blocked'), ('received', 'Received')], db_index=True, default='queued', max_length=12)),
                ('to_number', models.CharField(blank=True, max_length=32)),
                ('from_number', models.CharField(blank=True, max_length=32)),
                ('body', models.TextField()),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('error_detail', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.client')),
                ('dispatch_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='api.dispatchorder')),
                ('sent_by_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_messages_sent', to='api.agent')),
                ('sent_by_vendor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_sent', to='api.vendoruser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='api_memberm_client__46210c_idx'), models.Index(fields=['direction', 'status'], name='api_memberm_directi_4d2e14_idx')],
            },
        ),
    ]
