# Generated by Django 5.2.16 on 2026-09-18 15:54

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0277_member_messages_and_reminders'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillableItem',
            fields=[
                ('billable_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=120)),
                ('option_code', models.CharField(blank=True, db_index=True, max_length=60)),
                ('billing_category', models.CharField(db_index=True, max_length=120)),
                ('main_category', models.CharField(blank=True, max_length=120)),
                ('hcpcs_code', models.CharField(blank=True, max_length=20)),
                ('modifiers', models.CharField(blank=True, max_length=40)),
                ('vendor_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'billing_category', 'item'],
                'indexes': [models.Index(fields=['is_active', 'billing_category'], name='api_billabl_is_acti_b8d848_idx')],
                'constraints': [models.UniqueConstraint(fields=('item', 'billing_category'), name='uniq_billable_item_per_category')],
            },
        ),
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('admin_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_settings_updates', to='api.agent')),
            ],
            options={
                'verbose_name_plural': 'Billing settings',
            },
        ),
    ]
