# Generated by Django 5.2.16 on 2026-09-18 16:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0279_seed_billable_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='admin_fee_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='VendorPrice',
            fields=[
                ('vendor_price_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billable_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_prices', to='api.billableitem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_price_updates', to='api.agent')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='api.vendor')),
            ],
            options={
                'ordering': ['billable_item__sort_order'],
                'constraints': [models.UniqueConstraint(fields=('vendor', 'billable_item'), name='uniq_vendor_price_per_item')],
            },
        ),
    ]
