# Generated by Django 5.2.16 on 2026-09-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0280_vendor_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeprogram',
            name='borough',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
