# Generated by Django 5.2.16 on 2026-09-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0282_backfill_program_borough'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchproof',
            name='intervention_group',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
