# Generated by Django 5.2.16 on 2026-09-21 13:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0283_proof_intervention_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsettings',
            name='vendor_spend_cap',
            field=models.DecimalField(decimal_places=2, default=Decimal('9000.00'), max_digits=10),
        ),
    ]
