# Generated by Django 5.2.16 on 2026-09-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0284_vendor_spend_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='status_source',
            field=models.CharField(blank=True, choices=[('csv', 'CSV import'), ('api', 'Partner API')], max_length=8),
        ),
        migrations.AddField(
            model_name='deliveryorderproof',
            name='status_source',
            field=models.CharField(blank=True, choices=[('csv', 'CSV import'), ('api', 'Partner API')], db_index=True, max_length=8),
        ),
    ]
