# Generated by Django 5.2.16 on 2026-09-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0285_delivery_status_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='delivery_driver',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='delivery_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='delivery_route',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
