# Generated by Django 5.2.16 on 2026-09-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0286_delivery_driver_route_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='logo_s3_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vendor',
            name='logo_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
