# Generated by Django 5.2.16 on 2026-09-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0287_vendor_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='logo_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='logo_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
