# Generated by Django 5.2.16 on 2026-09-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0288_vendor_logo_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeprogram',
            name='parent_program',
            field=models.CharField(blank=True, choices=[('meals', 'Meals'), ('boxes', 'Boxes')], db_default='', db_index=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='activeprogram',
            name='service_type',
            field=models.CharField(blank=True, choices=[('clinically_appropriate_meals', 'Clinically Appropriate Meals'), ('medically_tailored_meals', 'Medically Tailored Meals (MTM)'), ('food_prescriptions', 'Food Prescriptions (Voucher / Boxes)'), ('produce_prescription', 'Produce Prescription/Voucher'), ('social_service_case_management', 'Social Service Case Management'), ('environmental_exposure_assessment', 'Environmental Exposure Assessment'), ('home_expense_assistance_repairs', 'Home Expense Assistance/Repairs'), ('environmental_modifications_accessibility', 'Environmental Modifications/Accessibility')], db_default='', default='', max_length=64),
        ),
    ]
