# Generated by Django 5.2.16 on 2026-09-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0292_all_food_prescriptions_to_produce'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeprogram',
            name='is_active',
            field=models.BooleanField(db_default=True, db_index=True, default=True),
        ),
    ]
