# Generated by Django 5.2.16 on 2026-09-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0294_deactivate_non_our_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeprogram',
            name='parent_program',
            field=models.CharField(blank=True, choices=[('meals', 'Meals'), ('boxes', 'Boxes'), ('home_remediation', 'Home Remediation')], db_default='', db_index=True, default='', max_length=32),
        ),
    ]
