# Generated by Django 5.2.16 on 2026-09-23 15:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0297_cam_service_type_to_mtm'),
    ]

    operations = [
        migrations.CreateModel(
            name='PauseReason',
            fields=[
                ('pause_reason_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='memberdietaryprofile',
            name='pause_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profiles', to='api.pausereason'),
        ),
    ]
