# Generated by Django 5.2.16 on 2026-09-23 20:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0299_seed_pause_reasons'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldReason',
            fields=[
                ('hold_reason_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('resume_policy', models.CharField(choices=[('none', 'No resume — an agent must close or re-open the case'), ('auto', 'Resumes automatically when the situation changes'), ('manual', 'An agent resumes when ready')], default='none', max_length=10)),
                ('resume_detail', models.CharField(blank=True, max_length=200)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='enrollmentverification',
            name='hold_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='api.holdreason'),
        ),
        migrations.AddField(
            model_name='stageevent',
            name='hold_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_events', to='api.holdreason'),
        ),
    ]
