# Generated by Django 5.2.16 on 2026-09-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0301_seed_hold_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentverification',
            name='held_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentverification',
            name='hold_resumed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='memberdietaryprofile',
            name='paused_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='memberdietaryprofile',
            name='resumed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
