# Generated by Django 5.2.16 on 2026-09-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0304_derived_status_hold_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchavailabilitywindow',
            name='purpose',
            field=models.CharField(choices=[('assessment', 'Assessment visit'), ('install', 'Installation')], db_index=True, default='assessment', max_length=20),
        ),
    ]
