# Generated by Django 5.2.16 on 2026-09-25 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0305_dispatch_window_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchproof',
            name='dispatch_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='api.dispatchitem'),
        ),
    ]
