# Generated by Django 5.2.16 on 2026-09-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0306_proof_dispatch_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoruser',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
