# Generated by Django 5.2.16 on 2026-09-25 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0307_vendor_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdmember',
            name='mobile_app_last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='mobile_app_must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='mobile_app_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='mobile_app_provisioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='mobile_app_provisioned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioned_member_app_users', to='api.agent'),
        ),
        migrations.CreateModel(
            name='MemberAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_ip', models.CharField(blank=True, max_length=64)),
                ('device_label', models.CharField(blank=True, max_length=120)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_tokens', to='api.householdmember')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['household_member', 'expires_at'], name='api_membera_househo_f9c9d8_idx')],
            },
        ),
    ]
